### ISSUE TITLE
Add Sense/Net to the 2019 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#114]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://community.sensenet.com/blog/2019/10/01/hacktoberfest-is-here), [Sense/Net](https://sensenet.com/) is participating in Hacktoberfest 2019 by giving away their own swag.

Please add Sense/Net to the 2019 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file. 

You will need to locate a blog post (or official tweet), the type of swag being offered, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to [register for Hacktoberest first by clicking here](http://hacktoberfest.digitalocean.com) and submit your pull requests after Oct 1st if you would like it to count for the official Hacktoberfest swag.

**Comment by Stukongeluk** [comment]
I'm on it! ;)

**Comment by madduci** [comment]
done

**Comment by crweiner** [comment]
Thank you to both @Stukongeluk and @madduci!! I like parts of both of your PRs and will be merging them both into one combined PR. Thank you again for making the Hacktoberfest Swag List even better for 2019!!
