### ISSUE TITLE
Add QMK to List

### ISSUE THREAD

**Issue by Kerl1310** [crweiner/hacktoberfest-swag-list#128]
Add QMK to list of participating organisations.

Source: https://hacktoberfest.qmk.fm/

**Comment by crweiner** [comment]
Hay @Kerl1310! Thank you very much for letting me know about QMK and their participation in Hacktoberfest!!! I'll have a look over your PR today and hopefully we can get them on the list soon. Thanks again! :smile:

**Comment by crweiner** [comment]
Being worked on in PRs #127 and #129
