### ISSUE TITLE
Add Strawberry to the 2019 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#131]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://twitter.com/patrick91/status/1178952690300272640?s=19), [Strawberry](https://github.com/strawberry-graphql) is participating in Hacktoberfest 2019 by giving away their own swag.

Please add Strawberry to the 2019 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file. 

You will need to locate a blog post (or official tweet), the type of swag being offered, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to [register for Hacktoberest first by clicking here](http://hacktoberfest.digitalocean.com) and submit your pull requests after Oct 1st if you would like it to count for the official Hacktoberfest swag.

**Comment by peterjgrainger** [comment]
can I take this on?

**Comment by CadenG150** [comment]
@peterjgrainger I already started it, about to make the pull request.

**Comment by peterjgrainger** [comment]
ok @CadenG150 np ! 👍

**Comment by crweiner** [comment]
Y'all are fast! :racing_car: :horse_racing: I always look at all the PRs, not just the first to submit it, and I'll combine PRs as needed to give people the most chances possible to make a meaningful contribution and celebrate Hacktoberfest.

**Comment by manishram** [comment]
I am not understanding how to proceed

**Comment by crweiner** [comment]
> I am not understanding how to proceed

Anyone is welcome to make this little project better by [following the Contributing guidelines here](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md). :smile:

**Comment by crweiner** [comment]
Added in #181
