### ISSUE TITLE
Add SAP to the Hacktoberfest 2019 Swag List

### ISSUE THREAD

**Issue by bh6erk** [crweiner/hacktoberfest-swag-list#140]
Hi! 

**SAP** are also giving away stuff this year:
https://blogs.sap.com/2019/10/04/lets-code-share-and-learn.-calling-abapers-to-next-edition-of-hacktoberfest/

**Comment by mohatagarvit** [comment]
Just wondering should this really be added. As only 1 person who makes the most PRs in ABAP projects will get a sap press book.

**Comment by crweiner** [comment]
Perhaps to the new **Top Contributors** section?? I'm not certain what I'll do yet but I'll consider it... :thinking:
