### ISSUE TITLE
Add Saleor to the 2019 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#144]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://twitter.com/getsaleor/status/1179370205895634946), [Saelor](http://getsaleor.com/) is participating in Hacktoberfest 2019 by giving away their own swag.

Please add Saelor to the 2019 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file.

You will need to locate a blog post (or official tweet), the type of swag being offered, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here](https://hacktoberfest.digitalocean.com/).

**Comment by f1xer** [comment]
Hello, I've added PR in #145

**Comment by HeroicHitesh** [comment]
@crweiner  #163  resolves this issue. You can close it now
