### ISSUE TITLE
Rearrange The Hacktoberfest Swag List?

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#16]
Now that this list of companies giving out swag for Hacktoberfest has grown quite long, does anyone have any thoughts on how it should be styled or rearranged? I kind of like the idea of putting DigitalOcean/GitHub/Twillio at the top, then Microsoft, then everyone else in alphabetical order.

Or, would you rather see it organized from least amount of work to most? Or best swag to worse swag?

Let me know your thoughts, and feel free to submit a PR if you figure out a decent way to organize the list. :+1:

**Comment by adriennetacke** [comment]
Have an idea.. I'll send a PR soon! :)

**Comment by crweiner** [comment]
Thank you @adriennetacke for your incredible work in rearranging the swag list! Your contribution is looking incredible in PR #22.

And also thank you to @EliSteger in PR #21 for taking the time to alphabetize the list and making it easier for all to read.

Looking forward to combining your two approaches soon. :+1: 

I love everyone helping out in the spirit of Hacktoberfest! :smile:

**Comment by crweiner** [comment]
The list has now been rearranged due to the work of @adriennetacke in PR #22 and PR #23. 

Thank you again! :-)
