### ISSUE TITLE
Add Software Mansion to the 2019 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#168]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://twitter.com/swmansion/status/1181221122471317504?s=19), [Software Mansion](https://swmansion.com/) is participating in Hacktoberfest 2019 by giving away their own swag.

Please add Software Mansion to the 2019 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file.

You will need to locate a blog post, the type of swag being offered, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here](https://hacktoberfest.digitalocean.com/).

**Comment by elysiacodes** [comment]
Working on this now :)

**Comment by crweiner** [comment]
Added in #170
