### ISSUE TITLE
Add scroll Up Button 

### ISSUE THREAD

**Issue by codewithdev** [crweiner/hacktoberfest-swag-list#193]
By adding an "Scroll to Up button" It would be easy to use. And create a good look in the Layout.

**Comment by obulaworld** [comment]
Does this also have to deal with adding the javascript for the scroll up button?

**Comment by crweiner** [comment]
> Does this also have to deal with adding the javascript for the scroll up button?

If you wish to insert a button [like this one](https://github.com/crweiner/hacktoberfest-swag-list/pull/200#issuecomment-541248473) then I'd be happy to take a look! :+1:

**Comment by adriaanvermeire** [comment]
This can be closed now, because of PR #224

**Comment by crweiner** [comment]
Thanks again!
