### ISSUE TITLE
Verify Companies for Hacktoberfest 2020 Participation

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#249]
Hello World! 🗺️ It's that time of year again; Hacktoberfest time! 🎃 🎉  At a time of social isolation, let's bring people together over the love of open source, learning something new, helping out, and some sweet swag.

We need to go through the list of companies that participated in Hacktoberfest 2019 to see if they are participating again in 2020. The 2019 release of the Swag List can be [found here](https://github.com/crweiner/hacktoberfest-swag-list/releases/tag/v2019). 

If they are participating and offering unique Swag, get them ready to add to the Swag List and let everyone know down below. 👇

**Comment by crweiner** [comment]
Several companies have web pages already up with their unique Hacktoberfest 2020 swag:

- [CircleCI (Orbtoberfest)](https://hacktoberfest.circleci.com/)
- [Nexmo / Vontage](https://developer.nexmo.com/hacktoberfest)
- [JetBrains](https://www.jetbrains.com/lp/hacktoberfest-2020/)

Still need to verify the companies from the [2019 Hacktoberfest Swag List](https://github.com/crweiner/hacktoberfest-swag-list/tree/v2019) and see if anyone from [2018](https://github.com/crweiner/hacktoberfest-swag-list/tree/v2018) is looking to make a return.

**Comment by Archis19** [comment]
can I work on this as well?

**Comment by Rugved-HACKER** [comment]
may i help you

**Comment by crweiner** [comment]
Absolutely@ If you know a company is participating, please add an Issue and submit a PR!

**Comment by Rugved-HACKER** [comment]
Ok have you merged me in this project

**Comment by crweiner** [comment]
> Ok have you merged me in this project

You're welcome to submit meaningful pull requests (PRs) that follow the [Hacktoberfest guidelines](https://hacktoberfest.digitalocean.com/details). If they are valid and helpful, then they will be merged into the live site. 👍

**Comment by Ameenrehman** [comment]
hello @crweiner ,
there are many organisations which are giving cool swags and T-shirt.
Some of them are Devfolio , Flutterwave.com, JabRef , Kong , Les-Tilleuls.coop , Parity , Uno, Xamarin and many more .
If you want to add these also please tell me i'll do .

**Comment by crweiner** [comment]
> Some of them are Devfolio , Flutterwave.com, JabRef , Kong , Les-Tilleuls.coop , Parity , Uno, Xamarin and many more .
> If you want to add these also please tell me i'll do .

If you could please verify that they are participating in Hacktoberfest 2020 and offering their own unique swag, then I'd love to have them here. 😄

**Comment by ritwikchakraborty123** [comment]
Hai I want to contribute

**Comment by crweiner** [comment]
Closing due to Hacktoberfest 2020 almost being over and it appears that all companies who are participating are already on the list. 😄

**Comment by remigioamc** [comment]
So sad you close de issue, just find out gatsby is offering [special edition glow in the dark Gatsby sticker, exclusively for Hacktoberfest contributors](https://github.com/gatsbyjs/gatsby/issues/27222).

Would you mind if I create the PR @crweiner ?

I'm really trying to make it this year but just start yesterday (a really complicated month)

**Comment by crweiner** [comment]
Hi @remigioamc! Yes, absolutely! Go ahead and submit a PR, you're all good ❤️

**Comment by crweiner** [comment]
Hacktoberfest 2020 is a wrap! Thank you so much to everyone who contributed to the Swag List and I hope you enjoy your sweet nerdy stuff! This repo will have the official 2020 release and tags soon.

Looking forward to an even better 2021 for us all. ❤️❤️
