### ISSUE TITLE
Update kramdown

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#251]
The version of kramdown in the [Gemsfile](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/Gemfile.lock) needs to be updated to version **2.3.0** or later. However, there is a dependency getting in the way that requires the older version of kramdown.

For Hacktoberfest, fork this repo, install and update [Jekyll](https://jekyllrb.com/), build the site, and let me know what you think needs to be done to update kramdown. 😄 🤓

**Comment by Khush1801** [comment]
Hi! Can I work on this?

**Comment by crweiner** [comment]
Hi @Khush1801! You're more than welcome to work on this. 😄

**Comment by SahilSayani** [comment]
HI I AM A BEGINNER CAN I WORK ON THIS PLEASE?
