### ISSUE TITLE
Hacktoberfest 2020 Swag Blocklist

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#256]
Sadly, not every company that participates in Hacktoberfest sees the value in being on this Swag List. While this project sends many, many meaningful contributions to amazing open source projects big and small, it will also inevitably lead to some spammy PRs from people just looking for stickers and a shirt. Most companies and maintainers totally understand that; it simply comes with the territory of [Hacktoberfest](https://hacktoberfest.digitalocean.com/).

Other companies don't see it that way. While I fundamentally disagree with their positions, I don't want to get into any more [Twitter battles](https://github.com/crweiner/hacktoberfest-swag-list/issues/44#issuecomment-535131859) over this. These are the companies who have asked to remain off of the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com):

- Umbraco (Please see Issue #156)

Any PRs that add a company on the list above will be closed. If you have questions regarding their stance on Hacktoberfest or this project, please ask the companies directly and feel free to have them reach me on [Twitter](https://twitter.com/c_dubbs) for further discussions. 

At the end of the day, you decide how you want to help those in the open source community. ❤️

**Comment by Ameenrehman** [comment]
hello @crweiner ,
there are many organisations which are giving cool swags and T-shirt.
Some of them are Devfolio , Flutterwave.com, JabRef , Kong , Les-Tilleuls.coop , Parity , Uno, Xamarin and many more .
If you want to add these also please tell me i'll do .

**Comment by crweiner** [comment]
Hi @adriaanvermeire, please use Issue #249 as a place to talk about companies offering Hacktoberfest swag for 2020 instead of here.

**Comment by SoftCreatR** [comment]
I've set up some "honeypots", where every PR will be instantly closed, locked and marked as invalid. As per Dev.to, too many invalid PRs may exclude you from the event for lifetime.
