### ISSUE TITLE
Add CircleCI to the 2020 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#257]
A good first issue for people celebrating Hacktoberfest! If you want for this to count towards Hacktoberfest, please submit your PR on October 1st!

Per [here](https://hacktoberfest.circleci.com/), [CircleCI](https://circleci.com/) is participating in Hacktoberfest 2020 (which they dub Orbtoberfest) by giving away their own swag.

Please add CircleCI to the 2020 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file.

You will need to locate the type of swag being offered and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here](https://hacktoberfest.digitalocean.com/).

**Comment by monizb** [comment]
Can I do this one?

**Comment by crweiner** [comment]
You are more than welcome to, @monizb! Thank you! Keep in mind that it's too early to count towards Hacktoberfest officially, so be sure to get your 4+ PRs in after October 1st. 😄

**Comment by crweiner** [comment]
CircleCI added in #267
