### ISSUE TITLE
Add Vontage/Nexmo to the 2020 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#258]
A good first issue for people celebrating Hacktoberfest! If you want for this to count towards Hacktoberfest, please submit your PR on October 1st!

Per [here](https://developer.nexmo.com/hacktoberfest), [Vontage/Nexmo](https://developer.nexmo.com/) is participating in Hacktoberfest 2020 by giving away their own swag.

Please add Vontage/Nexmo to the 2020 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file.

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here](https://hacktoberfest.digitalocean.com/).

**Comment by khushijindal** [comment]
Hey @crweiner! can I take up this issue? I am new to open source and this will be my first contribution to a public repo XD.

**Comment by khushijindal** [comment]
I am done with the work and will make a PR with the starting of Hacktoberfest 2020. 🙂

**Comment by crweiner** [comment]
Sweet, @khushijindal! I'm honored that you chose my little project to be your first PR! Be sure to double check your formatting and submit your PR when you're ready. 😎👍

**Comment by khushijindal** [comment]
I think so if I make the PR now, it will be counted towards Hacktoberfest 2020?

**Comment by hugovk** [comment]
Yes, it's already October somewhere in the world!

https://www.timeanddate.com/worldclock/kiribati/kiritimati

**Comment by crweiner** [comment]
Added in #266

**Comment by crweiner** [comment]
> Yes, it's already October somewhere in the world!
> 
By the way, great to see you again @hugovk! I hope you're doing well and it's nice having you around again for Hacktoberfest! 👋
