### ISSUE TITLE
Add JetBrains to the 2020 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#259]
A good first issue for people celebrating Hacktoberfest! If you want for this to count towards Hacktoberfest, please submit your PR on October 1st!

Per [here](https://www.jetbrains.com/lp/hacktoberfest-2020/), [JetBrains](https://www.jetbrains.com/) is participating in Hacktoberfest 2020 by giving away their own swag.

Please add JetBrains to the 2020 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file.

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here](https://hacktoberfest.digitalocean.com/).

**Comment by DaffyTheDuck** [comment]
Hello! can I work on this ?

**Comment by crweiner** [comment]
Absolutely, @DaffyTheDuck!! Keep in mind, it *may* be a bit early to count towards Hacktoberfest's official swag.

I mostly have a "first person to submit a good PR gets the merge" unwritten rule because I've had people say they'll add to or fix the List, then a week goes by with no PRs when others were willing to take up the Issue. 🙃

So, no Issues will be formally assigned to just one person in particular this year. With Hacktoberfest only a month long, sometimes we've got to be a bit more speedy. Hope that makes sense and I look forward to your PR! 👍

**Comment by DaffyTheDuck** [comment]
okay!  I'll make a pull request by tomorrow! thanks :smile:

**Comment by DaffyTheDuck** [comment]
I'm done with this work! i'll make the PR by tomorrow ! thanks :smile:
