### ISSUE TITLE
Collaboration with swag-for-dev 💯

### ISSUE THREAD

**Issue by swapagarwal** [crweiner/hacktoberfest-swag-list#26]
Hello from [devSwag.io](http://devswag.io/)! 👋

We maintain a similar repository, to curate swag opportunities for developers. 😎
I think we should consolidate all swag opportunities at one place. Thoughts? 🎉

https://github.com/swapagarwal/swag-for-dev/issues/136

**Comment by crweiner** [comment]
Hello @swapagarwal! 

Nice for you to reach out to me. :smile: I talked about your swag site when @benbarth let me know about his list in Issue # 8. 

In the spirit of Hacktoberfest and sweet, sweet, swag, I think it's great if we all share our lists around (I mean, everything is public after all, and clearly people are submitting pull requests to other people's swag lists after reading about it on another. That's pretty clear to see). I think we all have the same goal of letting the masses know about great ways to contribute to open source and get rewarded for doing so.

My swag list is just that, a Markdown list, while you and Ben have some nice sites to go with it. I might make a site at some point, but probably not for this Hacktoberfest. Not enough time left.

Anyway, what are your thoughts regarding combining forces? A joint repo where we all contribute? My main focus is Hacktoberfest at the moment and I'll gladly add to your swag-for-dev repo throughout the year if I see other things pop up. You've absolutely got the larger reach. :smile:

This is just a really long way to say I'm open to anything I can assist with. What are your thoughts about bringing all the lists together?

**Comment by swapagarwal** [comment]
> I think we all have the same goal of letting the masses know about great ways to contribute to open source and get rewarded for doing so.

Couldn't agree more!

> This is just a really long way to say I'm open to anything I can assist with. What are your thoughts about bringing all the lists together?

We have defined a JSON format [here](https://github.com/swapagarwal/swag-for-dev/blob/master/data.json) which could help in collaboration. This would allow folks to maintain their lists independently and import items from other lists. Let me know your thoughts on this?

Although, ideally, it'd be better for everybody to contribute to a central place - better for users as they'd get all items at one place - and better for us maintainers as it'd potentially avoid (some) duplication of effort. You could join our repo's team of collaborators if you like (+1 for synergy).

**Comment by crweiner** [comment]
> We have defined a JSON format [here](https://github.com/swapagarwal/swag-for-dev/blob/master/data.json) which could help in collaboration. This would allow folks to maintain their lists independently and import items from other lists. Let me know your thoughts on this?

That could certainly work for next year. As I said, I don't have high expectations for this list and initially just wanted a simple to read Markdown text file for people to reference. It also makes it really easy for a novice to submit a PR and get it checked off towards completing their goals for Hacktoberfest. Ideally I'd like to keep this as Markdown, maybe one day turned into a Jekyll or Hugo site or something, so if you know of any good automated ways to go from MD -> JSON and commit to a branch in this repo so you can grab it too, let me know. 

> Although, ideally, it'd be better for everybody to contribute to a central place - better for users as they'd get all items at one place - and better for us maintainers as it'd potentially avoid (some) duplication of effort. You could join our repo's team of collaborators if you like (+1 for synergy).

That's something I may entertain for next Hacktoberest. You certainly have the much bigger reach and audience. :smile: I only plan on maintaining this list once per year and probably don't have the time to be an active maintainer on devswag.io.

**Comment by swapagarwal** [comment]
Got it! Let's connect next year. 😇

**Comment by swapagarwal** [comment]
DMing you on Twitter. 🎉

**Comment by crweiner** [comment]
Just followed you! Looking forward to working with you! :+1:
