### ISSUE TITLE
Add MayaData to the 2020 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#260]
A good first issue for people celebrating Hacktoberfest! If you want for this to count towards Hacktoberfest, please submit your PR on October 1st!

Per [here](https://blog.mayadata.io/celebrate-hacktoberfest-2020-open-source-with-mayadata), [MayaData](https://mayadata.io/) is participating in Hacktoberfest 2020 by giving away their own swag through their [OpenEBS](https://openebs.io/) and [Litmus](https://litmuschaos.io/) projects. Their repos are [here for OpenEBS](https://github.com/openebs/openebs) and [here for Litmus](https://github.com/litmuschaos/litmus).

Please add MayaData to the 2020 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file.

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here](https://hacktoberfest.digitalocean.com/).

**Comment by kcclemo** [comment]
I'd like to help with this, please.

**Comment by crweiner** [comment]
You are more than welcome to, @kcclemo! Thank you! Keep in mind that it's too early to count towards Hacktoberfest officially, so be sure to get your 4+ PRs in after October 1st. 😄

**Comment by kcclemo** [comment]
Thank you!

It will probably be that long before I have enough time off work to get to it anyways. :-P

**Comment by crweiner** [comment]
No problem! I'd love to have this up by the start of Hacktoberfest. I can do it myself, but I like to give other people the chance to contribute. 😄 

I mostly have a "_first person to submit a good PR gets the merge_" unwritten rule because I've had people say they'll add to or fix the List, then a week goes by with no PRs when others were willing to take up the Issue. 🙃 

So, no Issues will be formally assigned to _just_ one person in particular this year. With Hacktoberfest only a month long, sometimes we've got to be a bit more speedy. Hope that makes sense and I look forward to your PR! 👍

**Comment by kcclemo** [comment]
Sounds good! I'll add it to my to-do for the first.

**Comment by crweiner** [comment]
MayaData has been added in #282 . @kcclemo, please feel free to submit any revisions or updates that you see fit if you wish to! 👍 😄
