### ISSUE TITLE
Add Globo to the 2020 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#261]
A good first issue for people celebrating Hacktoberfest! If you want for this to count towards Hacktoberfest, please submit your PR on October 1st!

Per [here](https://opensource.globo.com/hacktoberfest/), [Globo](https://github.com/globocom) is participating in Hacktoberfest 2020 by giving away their own swag.

Please add Globo to the 2020 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file.

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors). Please keep in mind, this swag will be limited to only a certain country, so be sure to clearly communicate that in their entry on the Swag List.

Be sure to register for Hacktoberest first by [clicking here](https://hacktoberfest.digitalocean.com/).

**Comment by Jassi10000** [comment]
Can I also make a Pull Request for this issue as am from India and GLOBO is accepting and distributing swags only within Brazillian Territory

**Comment by crweiner** [comment]
Yes, anyone can add a company to the Swag List. 😎👍

**Comment by Jassi10000** [comment]
But you wrote in the issue "Please keep in mind, this swag will be limited to only a certain country, so be sure to clearly communicate that in their entry on the Swag List."

I checked their validations for the swags . They are only distributing swags within Brazallian community
So should I do it or not????????

**Comment by DaffyTheDuck** [comment]
> But you wrote in the issue "Please keep in mind, this swag will be limited to only a certain country, so be sure to clearly communicate that in their entry on the Swag List."
> 
> I checked their validations for the swags . They are only distributing swags within Brazallian community
> So should I do it or not????????

This contribution is different than the contribution in the main repository!

**Comment by brecarv** [comment]
@crweiner I would like to work on this issue.

**Comment by brecarv** [comment]
I would like to work on this issue.

**Comment by crweiner** [comment]
Globo has been added in PR #274
