### ISSUE TITLE
Add Hasura to the 2020 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#262]
A good first issue for people celebrating Hacktoberfest! If you want for this to count towards Hacktoberfest, please submit your PR on October 1st!

Per [here](https://hasura.io/blog/hasura-joins-hacktoberfest-3rd-year-in-a-row/), [Hasura](https://hasura.io/) is participating in Hacktoberfest 2020 by giving away their own swag.

Please add Hasura to the 2020 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file.

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here](https://hacktoberfest.digitalocean.com/).

**Comment by RahilRehan** [comment]
Can I take this one?

**Comment by flyinspaghetti** [comment]
Can I please take this one?

**Comment by araut1** [comment]
I'm up for this.

**Comment by crweiner** [comment]
Hi all!

I mostly have a "_first person to submit a good PR gets the merge_" unwritten rule because I've had people say they'll add to or fix the List, then a week goes by with no PRs when others were willing to take up the Issue. 🙃 

So, no Issues will be formally assigned to _just_ one person in particular this year. With Hacktoberfest only a month long, sometimes we've got to be a bit more speedy. Hope that makes sense and I look forward to your PRs! 👍

**Comment by indranil-tiwary** [comment]
Hey @crweiner 
I have added the PR #280 
Please comment if you need any changes.
Thank you!

**Comment by crweiner** [comment]
Added in #271
