### ISSUE TITLE
Add Webiny to the 2020 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by jnv** [crweiner/hacktoberfest-swag-list#263]
Webiny also participates in Hacktoberfest per this article: https://dev.to/webiny/webiny-hacktoberfest-2020-49h4

> 💡 Contribute to Webiny and Win a Hacktoberfest T-Shirt
>
> -   a special Webiny Swag Pack ☺️
>
> Find out about Webiny's hacktoberfest issues at our GitHub [project board](https://github.com/webiny/webiny-js/projects/12) to keep track of the hacks of October at Webiny Open Source projects 🥳
>
> Go through the `hacktoberfest` labeled issues on the Webiny Open Source projects [here](https://github.com/search?q=org%3Awebiny+label%3Ahacktoberfest).
>
> Or, you can grab one of the ideas from the notes in the [project board](https://github.com/webiny/webiny-js/projects/12) and open a new issue for it. Make sure to tag the newly created issue with the `hacktoberfest` label.

**Comment by crweiner** [comment]
Sweet! Thanks for bringing this to my attention @jnv! 🎉🎉

Would you like to add them to the Swag List?

**Comment by jnv** [comment]
> Would you like to add them to the Swag List?

Thanks! I don't want to open PR for this, feel free to pick this up.

**Comment by avats-dev** [comment]
@crweiner I want to do this. Can I take this up?

**Comment by avats-dev** [comment]
Opened #275 , take a look. :rocket:

**Comment by Aamax14** [comment]
We are trying

**Comment by ritwikchakraborty123** [comment]
Sir I want to contribute

**Comment by ritwikchakraborty123** [comment]
Or any collaborate work will be fine for me

**Comment by crweiner** [comment]
All meaningful contributions that actually try to make this project better are welcome. ❤️❤️

**Comment by crweiner** [comment]
Added in #275
