### ISSUE TITLE
Add .mdlrc File To Configure markdownlint and Code Climate

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#29]
Create an `.mdlrc` file based on the official [configuration here](https://github.com/markdownlint/markdownlint/blob/25081c5b1a1312a111d22791197e6e2ad8092a0c/docs/configuration.md) that will ignore "Line Length" and "Multiple headers with the same content" flags in Code Climate.

See mdl rules: https://github.com/markdownlint/markdownlint/blob/v0.4.0/docs/RULES.md
See Code Climate docs: https://docs.codeclimate.com/docs/markdownlint
See further information in Issue #24

**Comment by gupta409** [comment]
I can work on this. Feel free to assign.

**Comment by crweiner** [comment]
Fixed in #43!!
