### ISSUE TITLE
Add Operation Code To Swag List

### ISSUE THREAD

**Issue by rohitjmathew** [crweiner/hacktoberfest-swag-list#291]
Hi 👋 

Operation Code is part of [Hacktober 2020](https://github.com/OperationCode/START_HERE) offering swag. 

They are also part of the [2019 list](https://github.com/crweiner/hacktoberfest-swag-list/tree/2019) and not part of the [block list](https://github.com/crweiner/hacktoberfest-swag-list/issues/256)

**Comment by crweiner** [comment]
Oh yay! It makes me so happy to see them back for another year! They're my example in the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) for a reason; I think they're great! 😄
