### ISSUE TITLE
Addressing the Hacktoberfest 2020 Spam

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#305]
Please [read the official response from DigitalOcean and the Hacktoberfest team here](https://hacktoberfest.digitalocean.com/hacktoberfest-update).

I recently learned that this project was featured in a YouTube video that caused the flood of spam pull requests for Hacktoberfest 2020.

I'm sick to my stomach to see this project manipulated in that way. This project exists to draw attention to companies going above and beyond during Hacktoberfest and incentivizing meaningful contributions towards repos that most people wouldn't think of helping. However, I always recognized that this List will send *some* people to the included repos for all the wrong reasons (just to get swag). What I hated seeing today is how *some* bad PRs turned into *most*. 

I must do something about it. I have already implemented a blocklist at #256 and will gladly add any company to it who wishes to be excluded from this project. But I've got to do more.

To give you a peak behind the curtain, the top referrals yesterday to HacktoberfestSwagList.com came from YouTube:

![Screen Shot 2020-10-01 at 3 12 19 AM](https://user-images.githubusercontent.com/23106097/94884286-0fd30000-043b-11eb-8c76-080f124f68e8.png)

As today went on, that changed into more direct traffic:

![Screen Shot 2020-10-01 at 10 36 19 PM](https://user-images.githubusercontent.com/23106097/94884330-2a0cde00-043b-11eb-9d03-f730f75a2688.png)

What this means is that thousands of people are accessing HacktoberestSwagList.com by referrals from the terrible YouTube video or typing in the URL directly. The next step is to see where the users are coming from:

![Screen Shot 2020-10-01 at 10 35 48 PM](https://user-images.githubusercontent.com/23106097/94884410-650f1180-043b-11eb-93cc-c093f9135f41.png)

There are **10 times** more visitors checking out the Swag List from India than the next highest country.

The YouTube video in question was from an Indian man and addressed to an audience who speaks Hindi. So, it makes perfect sense that the explosion of visitors this year from India are due to the YouTube video in question. 

I am now faced with a dilemma. I can use Netlify to redirect people visiting the site from India to the main Hacktoberfest Website instead of the Swag List. This will directly hinder those with the intent to spam by obfuscating the Swag List. However, I am well aware that it will still obviously live on GitHub and the 250+ forks of this repo. I also _really_ don't like censorship and this would get in the way of people with good intent. 

So, what do you think is best to do? Redirect traffic from India to the main Hacktoberfest website? Take down this repo? Something else? Please let me know because I've got to do something to play my part and stop the spam.

**Comment by monizb** [comment]
@crweiner this act is very sickening and I feel ashamed that it is happening from my country, I own a repo too and most of the PRs I got yesterday were spammy or added no value to the repository. Taking down this repo is in no way to stop these people from making these PRs. I think the best way to tackle this is to have more collaborators on this repository who will review the PRs and mark them spam/invalid without any questions asked. And if you want my help I'm more than happy to help you out :)

**Comment by monizb** [comment]
I also urge you to look at this article here: https://www.theregister.com/2020/10/01/digitalocean_hacktoberfest_pull_request_spam/

**Comment by crweiner** [comment]
> I also urge you to look at this article here: https://www.theregister.com/2020/10/01/digitalocean_hacktoberfest_pull_request_spam/

I've read all about it and I know what's going on; that's why I hate seeing this project dragged through the mud and causing others grief because it was directly shown off in that offending YouTube video. That's why I am leaning towards redirecting traffic to the main Hacktoberfest website instead of HacktoberfestSwagList.com for Indian viewers. Of course, the GitHub repo and all forks still work. But, I really don't like shooting down an entire country because I have had great contributions from people in India as well. 😄

**Comment by eldadfux** [comment]
@crweiner, Appwrite got tons of SPAM yesterday, but I'm not sure about blocking India as a whole is the best solution. We got lots of great maintainers from India and it would seem just wrong to generalise them all. What I would suggest is to add a big bold note against SPAM PR on hacktoberfestswaglist.com, this would at least be a starting point.

**Comment by peopledrivemecrazy** [comment]
Please check out this action https://github.com/marketplace/actions/check-and-reject-spam-prs to mitigate the problem now and for giggles https://twitter.com/shitoberfest

**Comment by sparkingdark** [comment]
This should be great to have a separate spam pr reviewer position and creating a repository about the information of the users who are doing spam. Then if we make a bot which take reference from the user blacklist repository and makes the spam pr invalid/spam.

**Comment by kunalrustagi08** [comment]
Please try this https://twitter.com/github/status/1311772722234560517?s=20 if it helps. 🤞🏽

**Comment by crweiner** [comment]
> @crweiner, Appwrite got tons of SPAM yesterday, but I'm not sure about blocking India as a whole is the best solution. We got lots of great maintainers from India and it would seem just wrong to generalise them all. What I would suggest is to add a big bold note against SPAM PR on hacktoberfestswaglist.com, this would at least be a starting point.

I've added that now in https://github.com/crweiner/hacktoberfest-swag-list/commit/4ee1fc7d5312bf1674188bdab596dae60f9edf19. Let me know if that looks ok, @eldadfux 

@peopledrivemecrazy, @sparkingdark, and @kunalrustagi08, the problem isn't so much me keeping up with the PRs here, it's the damage that is caused by people starting on my project then attacking companies on the list with spam PRs. I don't want to slow down or stop PRs here, I want to stop people from abusing the companies on the list.

**Comment by eldadfux** [comment]
@crweiner LGTM, now we just need to hope it will help to some degree 🤞🏻

**Comment by rohitjmathew** [comment]
@crweiner @eldadfux I understand at the end of the day its down to the individual and their value system but a small suggestion we can do is that we show a pop up on page load describing quality standards as described on the [Hacktober](https://hacktoberfest.digitalocean.com/details/#quality) site. Maybe this discourages people from doing this? What are your thoughts on this?

**Comment by indranil-tiwary** [comment]
@crweiner It's sad to see the surge for wrong purposes. I had hosted hacktoberfest 2018 and loved the collaboration in open source. But even if people are coming in more its good to see that people are celebrating open-source. The only issue we need to tackle is spam PRs.

**Comment by crweiner** [comment]
I'm up for trying a pop up message. Would anyone be able to help create a message and translate it into Hindi or other languages?

**Comment by SoftCreatR** [comment]
@crweiner Did you delete my comment?

**Comment by crweiner** [comment]
> @crweiner Did you delete my comment?

No, I don't delete comments! Are you [referring to this one?](https://github.com/crweiner/hacktoberfest-swag-list/issues/256#issuecomment-702528894)

**Comment by SoftCreatR** [comment]
Aww, sorry 😄

**Comment by khushijindal** [comment]
It is wrong that people are distorting to spammy pull requests to win some swag, which is for the motivation of people to come and contribute to open-source projects. But the solution of redirecting the whole of India is not the right solution as there are people from India too who want to learn and grow. @crweiner I can help translate to Hindi.

**Comment by indranil-tiwary** [comment]
> I'm up for trying a pop up message. Would anyone be able to help create a message and translate it into Hindi or other languages?

I can do that @crweiner

**Comment by hugovk** [comment]
Since the spam video was made private yesterday (https://twitter.com/florinpop1705/status/1311952466758504449) the spam flood stopped pretty quickly, at least from what I've seen.

Does that match up with this repo's stats?

And this was quite some time before Hacktoberfest's changes (https://hacktoberfest.digitalocean.com/hacktoberfest-update).

**Comment by aslafy-z** [comment]
In the two last hours, https://github.com/Joonsang1994/free-tshirts-stickers-and-swag-for-developers got a lot of spam PRs... A new video ?

**Comment by hugovk** [comment]
They were _closed_ 2 hours ago. Most were opened 2 days ago; the newest 15 hours ago, a bit of an outlier it seems.

**Comment by crweiner** [comment]
Thank you all for keeping your eyes on this issue and I'm happy to share that things have calmed down significantly. 

@hugovk is right; since the video in question went to private as well as the [large change to make Hacktoberfest opt-in](https://github.com/digitalocean/hacktoberfest/pull/596), I have noticed a very measurable decrease in spam and a stabilization of views to this repo and the website.

In order to have some transparency, here is anonymized analytics data for the last 24 hours (Oct 2nd 10PM Eastern Time to Oct 3, 10PM Eastern Time) for people visiting HacktoberfestSwagList.com:

![Screen Shot 2020-10-03 at 10 33 35 PM](https://user-images.githubusercontent.com/23106097/95005664-9c132d80-05c9-11eb-9ddc-5fa64df92249.png)

![Screen Shot 2020-10-03 at 10 33 57 PM](https://user-images.githubusercontent.com/23106097/95005665-a1707800-05c9-11eb-8670-05e3114c6c61.png)

![Screen Shot 2020-10-03 at 10 34 15 PM](https://user-images.githubusercontent.com/23106097/95005667-a59c9580-05c9-11eb-9638-6b65c73cf3f4.png)

As you can clearly see, direct traffic and Google now account for the vast majority of site visits, which is exactly what I expect. 

Looking over the last week, you can see that October 2nd was a major turning point where unique visitors and page views fell significantly. Normally for any other website, this might case panic and alarm. For me, this was a very welcome sight because that meant that the Swag List wasn't being used to target other repos anymore.

![Screen Shot 2020-10-03 at 10 44 19 PM](https://user-images.githubusercontent.com/23106097/95005783-3f644280-05ca-11eb-8168-0a28185ca122.png)

![Screen Shot 2020-10-03 at 10 44 35 PM](https://user-images.githubusercontent.com/23106097/95005784-45f2ba00-05ca-11eb-99a4-fb5c551669c2.png)

I give mad props to @MattIPv4 for weathering the storm, fielding all of the concerns on Twitter, and doing what he could to correct this issue. I also greatly thank the rest of the Hacktoberfest Team for their swift actions which seem to have saved the holiday for this year

So, going forward for this year, I see no reason to redirect traffic from India to the main Hacktoberfest website. I never really wanted to do that in the first place and I am glad that it never came to that. However, I am still 100% thinking about having a popup on the site reminding people to make meaningful contributions. This popup will display for *all* site visitors with a translation available in Hindi for people with an Indian IP address. @rohitjmathew, @khushijindal, and @indranil-tiwary, keep an eye out for a new Issue when I get this off the ground. I will need to rely on you to provide a translation in Hindi, if you would like to. If anyone else wishes to contribute language translations, I'd love to have that so we can help the greatest number of people possible!

This repo will **_remain opted in for Hacktoberfest 2020_** and all meaningful PRs are welcome. 💜

**Comment by sparkingdark** [comment]
Hey I can translate it in Bengali if required.😃

**Comment by eldadfux** [comment]
@crweiner, thank you for handling this so well and being so responsive and aware of the community concerns. Things look back to normal, and we still have 27 great days to enjoy Hacktoberfest 🤩.

**Comment by sparkingdark** [comment]
Yes and Digitalocean take several good steps to stop this.

**Comment by DeltaCoderr** [comment]
ikr

**Comment by tanishqchamola** [comment]
@crweiner Hey, I will be happy to help in translating to Hindi. 😄

**Comment by prithvidiamond1** [comment]
@crweiner I believe this problem is due to the fact that no matter how good or bad your pull requests are, if you can sneak as many as require in (which is so very possible given the amount of spam that each maintainer has to deal with), you get swag. Currently there is no in between a good or bad accepted pull request. Every accepted pull request counts and this will only fuel these spam contributors.

I feel Digital Ocean needs work with Github to create a rating system for contributors, like how we rate Uber drivers. Maintainers can rate a contributor for their work (i.e pull requests) and this will help not only the maintainers but also the contributors as future maintainers will know if someone is being spammy and contributors will know that their rating assures that they are not treated like the rest of the spam. This way maintainers can set repositories to only accept contributions from those with a minimum rating or higher. This will also decrease the necessary for the maturity time for pull requests if the minimum rating is very high.

I don't know if this is as good of an idea as it sounds in my head but if it is should I consider sharing it with Digital Ocean?

**Comment by crweiner** [comment]
I am very happy that the spam problem went away so quickly and additional measures didn't need to be taken to address it.

Thank you all for a wonderful Hacktoberfest 2020 and for all of your great contributions to the projects you love and the Swag List. ❤️❤️

I'll have a full writeup of how this year went on my [blog in a few weeks](https://chandlerweiner.com).

You all rock! Thank you again! ❤️❤️❤️❤️
