### ISSUE TITLE
Want to add umbraco in swag list

### ISSUE THREAD

**Issue by sparkingdark** [crweiner/hacktoberfest-swag-list#331]
Here is a company called umbraco offering the swags.
 https://umbraco.com/blog/hacktoberfest-2020/.
I want to add this to the repositorty. 

@crweiner

**Comment by crweiner** [comment]
Hi @sparkingdark, they are on the block list. Please see Issue #256. They have asked not to be Hacktoberest Swag List and I will be honoring that wish. #156 from last year shows their thoughts regarding this repo and how they wish to celebrate Hacktoberfest. 

I'd love to have them here, but I said I'd keep them off, so I shall keep my word. Better luck next year. 👍

**Comment by sparkingdark** [comment]
Thanks for the information.
