### ISSUE TITLE
Add Jekyll Target Blank Gem

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#361]
I am trying to get the Jekyll gem [Jekyll Target Blank](https://rubygems.org/gems/jekyll-target-blank) to work on this site so that links automatically open in a new tab in PR #359. However, even after [following these setup steps](https://keith-mifsud.me/projects/jekyll-target-blank), it doesn't seem to work. 

Anyone have any thoughts on what I am missing here? I assume that an older dependency is causing the links to not generate properly, but I'm not sure.

Thanks for the help! 😄

**Comment by strawberries73** [comment]
Hello @crweiner , I am fairly new.  I would like to try this issue.

**Comment by crweiner** [comment]
Hey there @strawberries73! 👋 Thanks for the help! Anyone who wants to is free to dive right in. 😊👍

**Comment by strawberries73** [comment]
Can you tell me the steps to run it after I have cloned the fork?

**Comment by strawberries73** [comment]
My apologies... I did not realize it was Ruby.  I am not familiar with Ruby.  I will opt out sorry.

**Comment by crweiner** [comment]
Hey @strawberries73! No need to apologize and I'm sure you can do it!! You don't need to dive into Ruby at all, Jekyll just runs on top of Ruby. It's really [easy to install and use](https://jekyllrb.com/docs/installation/) and you don't need to manually code anything at all. This site uses [Jekyll with Bundler and you can read about it here](https://jekyllrb.com/tutorials/using-jekyll-with-bundler/). 👍

**Comment by strawberries73** [comment]
I will give it a look soon.  I just finished Midterm/assignments and PR 3 for Hacktoberfest.  My weekend is busy so I can only promise Monday. :)

**Comment by crweiner** [comment]
Added in #366 👍
