### ISSUE TITLE
Update for Hacktoberfest 2021

### ISSUE THREAD

**Issue by LorenDB** [crweiner/hacktoberfest-swag-list#381]
It's Preptember, and hopefully we will have lots of companies and organizations with swag offers this year. I recognize that it is a bit early for a 2021 update right now, but I'm submitting this issue anyway in the spirit of readiness.

**Comment by crweiner** [comment]
Hey @LorenDB! 👋  You're absolutely correct and it's not too early; you're right on time! This is exactly the kick I needed to clean things up from 2020 and get ready for 2021. 😄 

In the meantime, while I get this repo ready for another great year, be sure to sign up for all of the official Hacktoberfest news at: https://hacktoberfest.digitalocean.com

Thank you for the reminder and let's have a wonderful Hacktoberfest this year!! 🎉

**Comment by crweiner** [comment]
A new Issue has been opened in #383 and a PR merged in #382 to get the Swag List ready for Hacktoberfest 2021!! If you know of any companies offering swag for 2021, please post about it in #383. 😄  👍

**Comment by LorenDB** [comment]
Looks like you have 2021 under control!
