### ISSUE TITLE
Verify Companies for Hacktoberfest 2021 Participation

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#383]
Hello beautiful nerds! 🤓  👋  It's that time of year again!! **Happy Hacktoberfest!!** 🍂 🎃 🎆 

![logo-hacktoberfest-full2 59799061](https://user-images.githubusercontent.com/23106097/133188169-6704b7d9-d4d8-4168-8ff4-8130477244f3.jpg)

With everyone stuck at home for another year, I'm sure many people have either taken the time to work on their coding skills or really, really want to get started learning. Hacktoberfest is **the** best way to get started and to be introduced to some great projects/companies you may have never heard of before! 

We need to go through the list of companies that participated in Hacktoberfest 2020 to see if they are participating again in 2021. The 2020 release of the Swag List can be found [here](https://github.com/crweiner/hacktoberfest-swag-list/releases/tag/v2020) and the [2020 branch is here](https://github.com/crweiner/hacktoberfest-swag-list/tree/2020).

If they are participating and offering unique Swag, get them ready to add to the Swag List and let everyone know down below. 👇

**Comment by crweiner** [comment]
AppWrite is participating again with unique swag, and they're going all out! 😎

[Confirmation tweet](https://twitter.com/eldadfux/status/1440282774045278214?s=19)

[AppWrite Hacktoberfest Website](https://hacktoberfest.appwrite.io/)

**Comment by crweiner** [comment]
LoginRadius is going to give out their own shirt!

https://www.loginradius.com/blog/async/hacktoberfest-2021/

I'm going to start reaching out to last year's companies on Twitter and anyone can feel free to post unique swag they find for Hacktoberfest 2021!

**Comment by Pranjalmishra30** [comment]
Milvus is participating in Hacktoberfest 2021
https://milvus.io/hacktoberfest-2021/

**Comment by crweiner** [comment]
Awesome job finding new companies, @Pranjalmishra30! It's great to see new companies offering unique swag this year! Yes, absolutely feel free to submit a PR adding them to the list. 👍👍

**Comment by Pranjalmishra30** [comment]
Thanks a lot. Is it allright if i open my PR after 1 oct so they count for hacktoberfest :)

**Comment by crweiner** [comment]
> Thanks a lot. Is it allright if i open my PR after 1 oct so that they count for hacktoberfest :)

You *can* wait, but I would advise against it. I'm sure there are many more meaningful contributions you can make during Hacktoberfest. Also, I'd like to have as near-complete a list as possible in the first 48 hours. Anyone can submit useful PRs, so someone else may add them before you raise a PR.

**Comment by HarshKumarChoudary** [comment]
What we have to do basically is to make a list of companies participating companies for Hacktober fest 2021, right? And then Make PR.

**Comment by HarshKumarChoudary** [comment]
If this is what we have to do, Then please assign this task to me. Thanks.

**Comment by crweiner** [comment]
Hello @HarshKumarChoudary! 👋 Yep, we're gathering companies that have already announced their participation in Hacktoberfest and are offering unique swag. If you find some great companies/people doing just that, then feel free to post about them here in this Issue or raise a PR to add them to the Swag List!

This isn't a job for just one person, as Hacktoberfest is all about the community. Looking forward to your contribution! 👍

**Comment by crweiner** [comment]
[LoginRadius](https://www.loginradius.com/blog/async/hacktoberfest-2021/) is offering their own unique Hacktoberfest swag this year! 🔒

**Comment by crweiner** [comment]
Milvus is also offering unique swag this year! 😎😎

https://discuss.milvus.io/t/join-hacktoberfest-2021-with-us/72

**Comment by rohitjmathew** [comment]
[Globo](https://hacktoberfest.globo.com/) have returned this year as well. Adding a PR for them

**Comment by rohitjmathew** [comment]
[Mattermost](https://mattermost.com/blog/hacktoberfest-2021/) have returned this year as well. Adding a PR for them

**Comment by HarshKumarChoudary** [comment]
app smith is participating in Hacktober Fest 2021 with swags.

**Comment by HarshKumarChoudary** [comment]
how to create a pull request here?

**Comment by HarshKumarChoudary** [comment]
How to Create Pull Request on this?

**Comment by crweiner** [comment]
> app smith is participating in Hacktober Fest 2021 with swags.

Appsmith was added in #388. If you need help getting started with your first pull request, I'd suggest [reviewing GitHub's docs](https://docs.github.com/en/github/collaborating-with-pull-requests) or searching around for the tons of blog posts and articles to help first-time contributors use Git, GitHub, and understand PRs. 😄

**Comment by crweiner** [comment]
Hey all you amazing nerds! 🤓 If you find a new company offering swag feel free to start your own Issue to document it. You can also submit a PR to add them if you wish to! I'll close this issue for now because we're good to go and well underway for Hacktoberfest 2021. 👍
