### ISSUE TITLE
[SEO] improve for URL sharing

### ISSUE THREAD

**Issue by tcarreira** [crweiner/hacktoberfest-swag-list#384]
When sharing this website on social platforms, there is no website preview because there are no proper meta tags for showing everything correctly.

We can test it on:
- https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fhacktoberfestswaglist.com%2F
- https://cards-dev.twitter.com/validator

The [Jekill SEO Tag](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md) plugin is responsible for handling everything. From my understanding, we only need to provide all data inside the `_config.yaml` file.

**Comment by crweiner** [comment]
Hey @tcarreira !👋

Great idea, this is a very easy thing to add for sure.

I took a look at the rendered HTML for the home page and saw this starting on line 7:
```html

<!-- Begin Jekyll SEO tag v2.6.1 --><title>Hacktoberfest 2021 Swag List | Hacktoberfest Swag List</title><meta name="generator" content="Jekyll v3.9.0" /><meta property="og:title" content="Hacktoberfest 2021 Swag List" /><meta property="og:locale" content="en_US" /><meta name="description" content="There are many companies giving out free swag for Hacktoberfest and this list seeks to find them all!" /><meta property="og:description" content="There are many companies giving out free swag for Hacktoberfest and this list seeks to find them all!" /><link rel="canonical" href="https://hacktoberfestswaglist.com/" /><meta property="og:url" content="https://hacktoberfestswaglist.com/" /><meta property="og:site_name" content="Hacktoberfest Swag List" /><script type="application/ld+json">{"publisher":{"@type":"Organization","logo":{"@type":"ImageObject","url":"https://hacktoberfestswaglist.com/img/Hacktoberfest_21.jpg"}},"description":"There are many companies giving out free swag for Hacktoberfest and this list seeks to find them all!","@type":"WebSite","headline":"Hacktoberfest 2021 Swag List","url":"https://hacktoberfestswaglist.com/","name":"Hacktoberfest Swag List","@context":"https://schema.org"}</script><!-- End Jekyll SEO tag -->

```

Maybe ```jekyll-sitemap``` is also adding the above, or the theme is? I'd have to look at the dependencies.

Either way, yeah, let's get that done. Seems easy enough to add! Great idea! 👏👏🤓🤓👍👍

**Comment by tcarreira** [comment]
I'll do it. ;)
