### ISSUE TITLE
Hacktoberfest: Change the color of Octocat and back to top buttons to match this year's theme

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#393]
This is a great Issue for a beginner to tackle for [Hacktoberfest](https://hacktoberfest.digitalocean.com/)! 🎃 🍂 

This repo uses Jekyll to generate a static site, hosted on Netlify at [Hacktoberfestswaglist.com](https://hacktoberfestswaglist.com). To make things a little easier to navigate, [Vanilla Back To Top](https://github.com/vfeskov/vanilla-back-to-top) is [embedded here](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/assets/js/vanilla-back-to-top.min.js) and referenced in the [HTML template here](https://github.com/crweiner/hacktoberfest-swag-list/blob/52128bb9ef2129a3671840ea99c0093e76cc929b/_layouts/default.html#L60).

Additionally, Octocat is used to point people back to this repo and [can be found here](https://github.com/crweiner/hacktoberfest-swag-list/blob/52128bb9ef2129a3671840ea99c0093e76cc929b/_layouts/default.html#L17). You[ can use this ](https://tholman.com/github-corners/)to help you figure out what line to change for Octocat's background color. 😄 

Using the [official Hacktoberfest Brand Guideline colors](https://hacktoberfest.digitalocean.com/brandguidelines), this is the perfect task for a **beginner** to update these two parts of the site to fit this year's Hacktoberfest color scheme., Please change them from purple to a color that matches this year's Brand Guidelines. Time to practice your CSS! 👍

**Comment by JanviRaina** [comment]
Hey! I found this interesting and I would like to work on this.

**Comment by krishna16sharma** [comment]
Hi! Please review my pull request solving this issue.
Thanks!

**Comment by crweiner** [comment]
Thank you for the help! 👍 Closed via #394
