### ISSUE TITLE
Add LoginRadius to the 2021 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#401]
A good first issue for people celebrating Hacktoberfest! If you want for this to count towards Hacktoberfest, please submit your PR on October 1st!

Per [here](https://www.loginradius.com/blog/async/hacktoberfest-2021/), LoginRadius is participating in Hacktoberfest 2021 by giving away their own swag.

Please add LoginRadius to the 2021 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.digitalocean.com/)

**Comment by Araon** [comment]
Can this assigned be assigned to me? @crweiner

**Comment by crweiner** [comment]
I don't typically assign Issues to one person; anyone is welcome to submit a meaningful PR for me to review. 👍
