### ISSUE TITLE
Add Milvus to the 2021 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#402]
A good first issue for people celebrating Hacktoberfest! If you want for this to count towards Hacktoberfest, please submit your PR on October 1st!

Per [here](https://milvus.io/hacktoberfest-2021/), Milvus is participating in Hacktoberfest 2021 by giving away their own swag.

Please add Milvus to the 2021 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.digitalocean.com/)

**Comment by Mridulbirla13** [comment]
Hey, I would like to fix issue #402

**Comment by crweiner** [comment]
You're welcome to take a crack at it! Anyone else can too! Looking forward to the PR. 👍

**Comment by crweiner** [comment]
Closed in #408
