### ISSUE TITLE
Eduhub Community Swag List 

### ISSUE THREAD

**Issue by SahityaRoy** [crweiner/hacktoberfest-swag-list#407]
From Eduhub Community we will be providing top contributor from our repository 
1. Cap
2. Sticker
3. 50 Amazon Voucher

**Comment by crweiner** [comment]
Hello @SahityaRoy! That's super awesome to hear! Do you happen to have a blog post, tweet, article, etc showing that you're offering this swag? I need a little more info to put into PR #413 , like providing a link verifying your swag and requirements.

Thank you! 😄
