### ISSUE TITLE
Add MayaData & OpenEBS to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#421]
A good first issue for people celebrating Hacktoberfest! If you want for this to count towards Hacktoberfest, please submit your PR on October 1st!

Per [here](https://blog.mayadata.io/celebrate-hacktoberfest-2021-support-open-source-with-mayadata-openebs), Maya Data and OpenEBS are participating in Hacktoberfest 2021 by giving away their own swag.

Please add them to the 2021 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.digitalocean.com/)

**Comment by riyaku11** [comment]
I would like to work on this

**Comment by crweiner** [comment]
Everyone is welcome to try and submit a PR! 👍😁

**Comment by crweiner** [comment]
This one is still open for anyone!! I'd love to give a PR to have someone else add them to the Swag List instead of me!

**Comment by jigarvyasidea** [comment]
I would like to work on this

**Comment by crweiner** [comment]
Please do, @jigarvyasidea! I've been wanting to get them on the list all day and was about to do it myself. 😅

**Comment by jawariaalvi32** [comment]
I would like to do this

**Comment by gauravgupta45** [comment]
Hey @crweiner, I believe there is no recent update on this issue, so taking up this. Creating PR asap.

**Comment by gauravgupta45** [comment]
> Hey @crweiner, I believe there is no recent update on this issue, so taking up this. Creating PR asap.

PR done. Let me know if I missed anything. #441

**Comment by crweiner** [comment]
Added in #441
