### ISSUE TITLE
Add Zup to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#422]
A good first issue for people celebrating Hacktoberfest! If you want for this to count towards Hacktoberfest, please submit your PR on October 1st!

Per [here](https://insights.zup.com.br/hacktoberfest), ZUP is participating in Hacktoberfest 2021 by giving away their own swag.

Please add them to the 2021 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.digitalocean.com/)

**Comment by Mridulbirla13** [comment]
Hey @crweiner , I would like to contribute in this issue.

**Comment by crweiner** [comment]
Everyone is welcome to! Go right ahead! 👍 Looking forward to your PR. 😁

**Comment by Rathore-Devraj** [comment]
I would like to contribute in this issue.

**Comment by crweiner** [comment]
Closed via #424
