### ISSUE TITLE
Add Stack Builders to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#423]
A good first issue for people celebrating Hacktoberfest! If you want for this to count towards Hacktoberfest, please submit your PR on October 1st!

Per [here](https://www.stackbuilders.com/news/it-s-hacktoberfest-time), Stacj Builders is participating in Hacktoberfest 2021 by giving away their own swag.

Please add them to the 2021 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.digitalocean.com/)

**Comment by beheradibas** [comment]
Can I work on this?

**Comment by beheradibas** [comment]
@crweiner Stack Builders participated in Hacktoberfest 2020, and their website still shows details for HacktoberFest2020. So, is the organization participating this year too? 
If it is participating, I would be delighted to be assigned this issue.

**Comment by crweiner** [comment]
I believe that they are based upon the Google Doc they linked to in their Hacktoberfest blog post: https://docs.google.com/forms/d/1C6ECEGE2pk3mNmeGhh4cct4Uf-lvJ4xu0ufDym612R4/viewform?edit_requested=true

**Comment by beheradibas** [comment]
I have gone through their blog and I can add the necessary details to README.md. Please assign me this issue.

**Comment by tabhay563** [comment]
Can i work on this issue please assign me

**Comment by vikramadityasinghs** [comment]
could i work on this? seems like its hacktoberfest inception would be fun!

**Comment by crweiner** [comment]
Added in #436
