### ISSUE TITLE
Add NativeScript to the 2021 Hacktoberfest Swag List!

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#430]
A good first issue for people celebrating Hacktoberfest! 

Per [here](https://twitter.com/NativeScript/status/1443768781931638784) and [here](https://blog.nativescript.org/hacktoberfest-2021/index.html), NativeScript is participating in Hacktoberfest 2021 by giving away their own swag. 😄 

Please add them to the 2021 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.digitalocean.com/)

**Comment by AnuragYadav365** [comment]
Hey, @crweiner I would like to contribute to this issue! Should I make a PR regarding this?

**Comment by crweiner** [comment]
@AnuragYadav365 You're absolutely welcome to! If you also wrap up some things in PR #425, I can get that merged and on the live list too. 😄

**Comment by AnuragYadav365** [comment]
@crweiner sure! 👍

**Comment by Aniket-508** [comment]
@crweiner Hey, can I work on this issue since its not already assigned?

**Comment by AnuragYadav365** [comment]
Hey @Aniket-508 good to see that you are interested in this issue, I am already working on this issue! Just going to make a PR in few minutes. 👍

**Comment by crweiner** [comment]
Added in #436
