### ISSUE TITLE
Gather Companies Offering Swag for Hacktoberfest 2019

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#44]
Hello all!

With Hacktoberfest 2019 right around the corner, is anyone yet aware of companies committed to offering swag?

You can review the [2018 branch here](https://github.com/crweiner/hacktoberfest-swag-list/tree/2018) to see the list of companies that participated last year. I've heard back from only one of them with a commitment to sponsor swag again this year.

If you hear of a swag opportunity on the horizon for 2019, let us know by posting here. 

~~However, don't submit a Pull Request or a new Issue yet until Hacktoberfest begins and you've signed up on the [DigitalOcean](https://hacktoberfest.digitalocean.com/) website~~ 
**You can submit your PRs now if you wish to add companies to the list before Hacktoberfest officially begins, but keep in mind that any PRs you make before you [register for Hacktoberfest](https://hacktoberfest.digitalocean.com/) (or before Oct 1st) won't count toward the official Hacktoberfest swag.**

I just want to gather things in one place until Hacktoberfest 2019 begins.

Once the most festive of holidays does start, then please submit your PRs and Issues to add companies to the list, and be sure to read the [Contributing guidelines](https://github.com/crweiner/hacktoberfest-swag-list/blob/2019/CONTRIBUTING.md)! I want as many people to get their swag as possible!

**Comment by crweiner** [comment]
[Kong](https://konghq.com/) has made public their intentions to offer their own swag for Hacktoberfest via [Twitter](https://twitter.com/thekonginc/status/1172269515884912640?s=19)

**Comment by crweiner** [comment]
[LBRY](https://lbry.com/) has also made their intentions to offer a swag t-shirt via Twitter [here](https://twitter.com/jsigwart/status/1175054393541922817?s=19) and [here](https://twitter.com/jeremykauffman/status/1175053927894704129?s=19)

**Comment by crweiner** [comment]
[OpenEBS](https://www.openebs.io/) has also stated that they'll be offering swag via [Twitter](https://twitter.com/_nisanta_/status/1175059143784157185?s=19), specifically a t-shirt for every successful merged PR in any of the [OpenEBS Repos](https://github.com/openebs) with other grand prizes and giveaways to be announced later.

**Comment by crweiner** [comment]
[Auth0](https://auth0.com/) and [Nexmo](https://www.nexmo.com/) are **_not_** offering their own swag for Hacktoberfest this year per Twitter [here](https://twitter.com/Auth0Community/status/1176064580075888640?s=19) and [here](https://twitter.com/NexmoDev/status/1176101592858333185?s=19)

**Comment by gagandeepp** [comment]
https://circleci-public.github.io/hacktoberfest/#/ 
Circle CI will be offering their swags

**Comment by crweiner** [comment]
Sweet! Thanks @gagandeepp!! That shirt looks mighty fine. :nerd_face:

**Comment by crweiner** [comment]
Hi @gagandeepp, I changed my mind about holding off on adding companies to the list until Hacktoberfest begins because I'd like to hit the ground running with something workable on day 1. I merged CircleCI's involvement in #46 and I'd highly encourage you to add other companies to the list or fix the [markdown lint errors to appease the bots](https://codeclimate.com/github/crweiner/hacktoberfest-swag-list/pull/46) so long as you know that any PRs you submit before signing up for Hacktoberfest won't count towards the official swag.

**Comment by crweiner** [comment]
[Appwrite](https://appwrite.io/) was added to the swag list in PR #47 by one of the developers! It's great to see new companies joining in!

**Comment by gagandeepp** [comment]
https://twitter.com/GopinathLangote/status/1176436040439148545

1build will be offering swag to

**Comment by crweiner** [comment]
> https://twitter.com/GopinathLangote/status/1176436040439148545
> 
> 1build will be offering swag to

Humm...it's not clear if they are offering their own unique swag or just stating that you can earn the main DigitalOcean/Dev.to Hacktoberfest shirt. Do you have any clarification or other info to share?

**Comment by crweiner** [comment]
It seems like [Umbraco](https://umbraco.com) will be offering their own swag for Hacktoberfest 2019 according to a sneak peek [this blog post](https://umbraco.com/blog/the-pr-team-chronicles-september-2019/). However, one of the Umbraco devs doesn't seem to like this little project all that much and requested on Twitter [here](https://twitter.com/cultiv/status/1176901157429682177?s=19) and [here](https://twitter.com/cultiv/status/1176909684206444545?s=19) to not be added to the list...

So....yeah.... I don't know what to do besides not merge a PR adding them here. Surely they'll be added to other websites and blogs that track Hacktoberfest swag offerings. 

Wanting to pull in @benbarth and @swapagarwal to see if they've had a company say this before and what they plan on doing with their own lists with regards to Umbraco....

**Comment by benbarth** [comment]
Thanks for the heads up @crweiner. I've never seen this before. I've removed Umbraco from my list and added a comment to the [Umbraco 2019 ticket](https://github.com/benbarth/hacktoberfest-swag/issues/51).

**Comment by crweiner** [comment]
I know Ben, it just seems so odd. To go through the hassle to make swag, tease it, host hackathons, write an upcoming blog post about the swag, but **_no_** 'don't share our swag on your little Markdown list because it'll attract a few bad apples' just doesn't make any marketing sense...

**Comment by crweiner** [comment]
Sadly no [SendGrid](https://sendgrid.com/) swag this year [per this Tweet](https://twitter.com/WieEinFuchs/status/1176580410706280449)

**Comment by crweiner** [comment]
A new company, [Uno](https://platform.uno/) is giving away their own swag for Hacktoberfest! Yay!!! We've got another new one! See their [blog post here](https://platform.uno/uno-is-joining-hacktoberfest-2019/)

**Comment by gagandeepp** [comment]
https://www.accordproject.org/events/hacktoberfest-2019/

**Comment by crweiner** [comment]
> https://www.accordproject.org/events/hacktoberfest-2019/

Sweet!! That's another great one! Thanks for finding the Accord Project! :smile:

**Comment by crweiner** [comment]
Operation Code has [updated their repo](https://github.com/OperationCode/START_HERE) from last year's Hacktoberfest to include info for 2019 and how to earn their swag for this year!!

**Comment by crweiner** [comment]
[Hasura](hasura.io) has joined Hacktoberfest 2019 with their own swag again per [their blog post](https://blog.hasura.io/hasura-joins-hacktoberfest-2019/)!

**Comment by gagandeepp** [comment]
https://substrate.dev/hacktoberfest/

**Comment by jacobtomlinson** [comment]
We send out opsdroid stickers to our contributors all year round but for hacktoberfest we will be included a limited edition one too.

https://medium.com/opsdroid/contributor-sticker-packs-738058ceda59

**Comment by daniloff200** [comment]
Valor Software (creators & maintainers of ngx-bootstrap) take part this year too ! 
Check out our blog post  : https://valor-software.com/articles/hacktoberfest-2019-is-coming-and-ngx-bootstrap-strives-for-your-attention.html

**Comment by crweiner** [comment]
> We send out opsdroid stickers to our contributors all year round but for hacktoberfest we will be included a limited edition one too.
> 
> https://medium.com/opsdroid/contributor-sticker-packs-738058ceda59

![Thank You!](https://media.giphy.com/media/QAsBwSjx9zVKoGp9nr/giphy.gif)

Hay there @jacobtomlinson!! Thanks for letting us know about opsdroid and for offering your own sticker swag for Hacktoberfest!! I added Issue #59 so someone can add your project to the list. :smile: I love seeing new companies participate in Hacktoberfest every year and I hope you enjoy the holiday. Thanks again!

**Comment by crweiner** [comment]
> Valor Software (creators & maintainers of ngx-bootstrap) take part this year too !
> Check out our blog post : https://valor-software.com/articles/hacktoberfest-2019-is-coming-and-ngx-bootstrap-strives-for-your-attention.html
> 
> Gonna create a PR with adding this info to the list soon

Hello @daniloff200!! Thank you so very much for participating in Hacktoberfest and offering your own swag for ngx-bootstrap! You guys rock! I've added Issue #60, so be sure to tag that issue when submitting your PR. 
![Thanks Partner](https://media.giphy.com/media/3oz8xIsloV7zOmt81G/giphy.gif)

Thanks again for participating in Hacktoberfest, offering your own swag, and for spreading the word here on this little project! :smile:

**Comment by crweiner** [comment]
Now that Hacktoberfest 2019 has officially started, please [Post a new issue](https://github.com/crweiner/hacktoberfest-swag-list/issues/new) when you discover a new company offering Hacktoberfest swag. Thanks all!
