### ISSUE TITLE
Add Symbl.ai to hacktoberfest swag list   

### ISSUE THREAD

**Issue by sbalikondwar** [crweiner/hacktoberfest-swag-list#462]
Hi guys,
We people at Symbl.ai are celebrating hacktoberfest for the first time. We have some repositories open-sourced for developers to contribute. We also have cool swags planned, for more information, I will create a PR and add it to this list.

Website: http://symbl.ai

**Comment by crweiner** [comment]
Good to know, @sbalikondwar! Thanks for letting us know you're going the extra mile for Hacktoberfest! Please be sure to also include a link to an official blog post, tweet, or something to verify the swag that Symbl.ai is offering. 👍

**Comment by crweiner** [comment]
Thank you all! Added in #467. 👍 🎆 😄
