### ISSUE TITLE
Add Umbraco to the 2021 Hacktoberfest Swag List!

### ISSUE THREAD

**Issue by moingshaikh** [crweiner/hacktoberfest-swag-list#486]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://umbraco.com/blog/hacktoberfest-2021-contribute-to-the-all-new-umbraco-9/), Umbraco is participating in Hacktoberfest 2021 by giving away their own swag. 😄

Please add them to the 2021 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.digitalocean.com/)

**Comment by crweiner** [comment]
No worries, thanks for being on the lookout for more opportunities! 👍
