### ISSUE TITLE
Add Sourcegraph to the Hacktoberfest Swag List!

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#498]
A good first issue for people celebrating Hacktoberfest! 

Per [here](https://dev.to/sourcegraph/happy-hacktoberfest-from-sourcegraph-2dc3) and [here](https://twitter.com/sourcegraph/status/1448758135511003139?s=20), Sourcegraph is participating in Hacktoberfest 2021 by giving away their own swag. 😄 

Please add them to the 2021 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.digitalocean.com/)

**Comment by nicoolel** [comment]
hi, can i work on this issue?
