### ISSUE TITLE
Add CI with CircleCI

### ISSUE THREAD

**Issue by felicianotech** [crweiner/hacktoberfest-swag-list#50]
Before we can create a CircleCI config file we need to know:

- what the site is built with: Jekyll
- where it's hosted: ?
- the deployment process (how it gets from git to the server): ?
- how is the website being tested: ?

**Comment by crweiner** [comment]
Hay Ricardo! Good to see you and thanks for the helping hand!

Yes, this is a Jekyll site, built/deployed and hosted on Netlify. They automatically build and deploy with each commit to master and deploy a preview for each PR. It's being tested by either running a localhost copy and/or by opening a PR myself and have Netlify build a PR preview (when I'm particularly lazy). 

My goal with this project is to make it as simple as can be as it has many new and first-time contributors. I want for them to easily see the results of their PR and make it as painless for me to manage once Hacktoberfest starts getting in full swing. 

Being that it's low traffic and no budget, it's a good place to start and learn about CircleCI for sure! 

If this grows too large for the free tier of Netlify, then I plan to deploy the site via BunnyCDN (upload via FTP).

I have a goal of trying to figure out how to use a CI/CD tool to run a Python website scraper that outputs to a CSV file, then use that CSV as source for text on a page built by Jekyll, but that's a whole different can of worms for a different site. 😂
