### ISSUE TITLE
The favicon can lose it's background and be transparent instead

### ISSUE THREAD

**Issue by Shweta200126** [crweiner/hacktoberfest-swag-list#502]
The favicon as you can see has white background around it (in square/ rectangle) , you can see here:
![image](https://user-images.githubusercontent.com/72426535/137580317-dcad9ce9-62a5-4dfb-ae6a-514fa7a0b734.png)

I understand it's not a big thing but I'll appreciate it, if it could be changed to this instead, without a background
![H-icon-light](https://user-images.githubusercontent.com/72426535/137580466-5fcf00af-072a-43ac-9f06-eb7d184f118f.png)

I would love to work on this if its okay.

**Comment by baznamit** [comment]
That's better. 👍

**Comment by Shweta200126** [comment]
Cool, will do it just now :)

**Comment by 5hraddha** [comment]
Hey @crweiner, can I work on this?

**Comment by crweiner** [comment]
Hey all! The favicon comes from the ```jekyll-seo-tag``` gem, which is a dependency of ```github-pages``` [found here](https://github.com/crweiner/hacktoberfest-swag-list/blob/97a0b84a44496ce345ee416603aff9f44e9e7fc3/Gemfile#L2). It presents the ```favicon.ico``` file [located here](https://github.com/crweiner/hacktoberfest-swag-list/blob/97a0b84a44496ce345ee416603aff9f44e9e7fc3/favicon.ico).

I'm not sure if the .ico file supports full transparency, so if not, then you'd need to use a .png file for the favicon. [Following these steps](https://medium.com/@xiang_zhou/how-to-add-a-favicon-to-your-jekyll-site-2ac2179cc2ed) should help you out, and I'd recommend trying to add the favicon link/definition [around here](https://github.com/crweiner/hacktoberfest-swag-list/blob/97a0b84a44496ce345ee416603aff9f44e9e7fc3/_layouts/default.html#L10).

If that doesn't work, there is a [Jekyll Gem here](https://afaundez.gitlab.io/jekyll-favicon-example/) to help, but I'm not sure it plays nicely with GitHub pages, [per their repo](https://github.com/afaundez/jekyll-favicon).

Hope that helps point you all in the right direction! 😄 If you need another nudge or hint, please let me know! 👍 🤓
