### ISSUE TITLE
Add Devtron to the 2021 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#505]
A good first issue for people celebrating Hacktoberfest! 

Per [here](https://github.com/devtron-labs/hacktoberfest2021), Devtron is participating in Hacktoberfest 2021 by giving away their own swag. 😄 

Please add them to the 2021 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.digitalocean.com/)

**Comment by areyaar** [comment]
Assign Me!

**Comment by crweiner** [comment]
Hey @areyaar, I don't typically assign Issues. Anyone is welcome to submit a PR following the Contributing docs. 👍

**Comment by crweiner** [comment]
OMG, I must be blind! Thank you @shiningflutes! I don't know how I missed that! 😅
