### ISSUE TITLE
Did anyone get their hacktober 2021 swag? 

### ISSUE THREAD

**Issue by AmirNaghibi** [crweiner/hacktoberfest-swag-list#516]
I know this is not related but I couldn't find any information online. Feel free to close it after a while. 

I'm from Canada and filled out the swag form in October 2021 but still haven't received anything.

**Comment by crweiner** [comment]
Hey @AmirNaghibi! 👋

No, I don't believe so. I haven't gotten my official swag yet. Usually the [Hacktoberfest Twitter account](https://twitter.com/hacktoberfest) is good at retweeting when people post pics of their swag and I haven't seen any yet.

Please share pics when you do! Hope you had a great Hacktoberfest! 🤓
