### ISSUE TITLE
Add Kong to the 2019 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#52]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://github.com/crweiner/hacktoberfest-swag-list/issues/44#issuecomment-533573229), [Kong](https://konghq.com/) is participating in Hacktoberfest 2019 by giving away their own swag.

Please add Kong to the 2019 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file. 

You will need to locate a blog post (or official tweet), the type of swag being offered, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to [register for Hacktoberest first by clicking here](http://hacktoberfest.digitalocean.com) and submit your pull requests after Oct 1st if you would like it to count for the official Hacktoberfest swag.

**Comment by gagandeepp** [comment]
Please assign this to me

**Comment by crweiner** [comment]
Go for it, my good man! Please only work on this company for now and save the other PRs/Issues for other people trying to contribute for Hacktoberfest too. I want to help spread the swag around!  :smile:

**Comment by crweiner** [comment]
I actually think that PRs are currently counting because it's already Oct 1st in Japan/Korea/Australia/New Zealand, etc. You can submit your PR and check your [Hacktoberfest Profile](https://hacktoberfest.digitalocean.com/profile) to see if it shows up there (I have no idea how long it takes to appear),

**Comment by gagandeepp** [comment]
@crweiner Will update this if there is any update from kong

**Comment by obulaworld** [comment]
Is this still open?

**Comment by crweiner** [comment]
I don't think that Kong is offering unique swag for Hacktoberfest so I am not looking to add them to this list.
