### ISSUE TITLE
Verify Companies for Hacktoberfest 2022 Participation - Setup The Hacktoberfest Swag List for 2022

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#528]
Hello amazing Hacktoberfest community! 👋 🤓 It's that time of year again; Happy Hacktoberfest!!! 🍂  🌲 👕

 
<img width="576" alt="Hfest-Logo-2-Color-Manga@2x" src="https://user-images.githubusercontent.com/23106097/189694999-1bedd863-a11b-49ea-a106-28a2973b806a.png">

Check out the sweet new site over at https://hacktoberfest.com/ for this year 🤯 

I hope you all are doing well, wherever you are in the world, and have been working on your skills to make some meaningful contributions for Hacktoberfest 2022!

As I work on getting the Swag List ready for another great year, **I need your help** to go through the list of companies that participated in Hacktoberfest 2021 to see if they are participating again in 2022. The [official v2021 release of the Swag List is here](https://github.com/crweiner/hacktoberfest-swag-list/releases/tag/v2021) and can also be accessed [via the 2021 branch here](https://github.com/crweiner/hacktoberfest-swag-list/tree/2021).

---

**Remember**, this repo is specially to give a boost to companies that go above and beyond for Hacktoberfest by offering their own unique swag for the holiday. I'm incredibly proud that this repo has helped many small orgs get a boost in meaningful PRs during Hacktoberfest by shouting them out on the Swag List!! The DMs I get at the end of each year warm my heart!! ❤️‍🔥 

### My goal remains the same as always: connecting heartfelt contributors with companies/orgs that love Hacktoberfest and want to celebrate this amazing holiday. 

---

If you hear that companies are going above and beyond to offer their own swag in celebration of Hacktoberfest, let everyone know down below so the Swag List can be as complete as possible on day 1. 👇

Some companies do not want to participate on this list, and that's ok. [The official list will remain here](https://github.com/crweiner/hacktoberfest-swag-list/issues/256) and be pinned to the top of the Issues tab.

Remember that all of the usual rules apply for Hacktoberfest and I _highly encourage you_ [to review the official documentation before participating this year](https://hacktoberfest.com/participation/). [Spam is not tolerated at all and there is a strict 2 strikes and you're out policy across all Hacktoberfest-participating repos](https://hacktoberfest.com/participation/#pr-mr-details).[ Meaningful low-code or no-code contributions are valid](https://hacktoberfest.com/about/#low-or-non-code), spam is not.

Let's have another fun year! 🎆 🥳 🎉

**Comment by crweiner** [comment]
Looks like [Camunda](https://camunda.com/hacktoberfest2022/) is participating this year with both swag and planting trees! 👕 🌲

**Comment by crweiner** [comment]
Hi @IamGuneet! 👋 Good question! [The rules for PRs can be found here](https://hacktoberfest.com/participation/#pr-mr-details). In summary:

* The repo itself must be tagged as `hacktoberfest`, to show that they are opted-in for Hacktoberfest, and the PR must be merged, labeled as `HACKTOBERFEST-ACCEPTED`, or receive an approving review.
_or_
* Your PR must be labeled `HACKTOBERFEST-ACCEPTED` in any repo that isn't in an explicitly opted-in repo. 

Your PR must follow the [Hacktoberfest Values](https://hacktoberfest.com/participation/#values) and [absolutely CANNOT be spam](https://hacktoberfest.com/participation/#spam). Bad/spammy repos are excluded and[ I report a lot of them each year.](https://hacktoberfest.com/report/).

**Comment by IamGuneet** [comment]
@crweiner Thank you.

**Comment by crweiner** [comment]
[Appwrite](https://hacktoberfest.appwrite.io/?utm_source=web&utm_medium=swaglist&utm_campaign=hacktoberfest) is back for Hacktoberfest 2022! We're incredibly lucky to have them and they will be sponsoring the Hacktoberfest Swag List for the second year in a row! 🎉  [Here's their blog post for this year](https://appwrite.io/hacktoberfest)

**Comment by tanmoy27112000** [comment]
add Invertase to the company list  PR: https://github.com/crweiner/hacktoberfest-swag-list/pull/543

**Comment by crweiner** [comment]
Hacktoberfest is officially on, so I'll close this Issue. Please submit all PRs as usual now if you find a new organization to add to the list! 😄
