### ISSUE TITLE
Add LBRY to the 2019 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#53]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://github.com/crweiner/hacktoberfest-swag-list/issues/44#issuecomment-533585664), [LBRY](https://lbry.com/) is participating in Hacktoberfest 2019 by giving away their own swag.

Please add LBRY to the 2019 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file. 

You will need to locate a blog post (or official tweet), the type of swag being offered, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to [register for Hacktoberest first by clicking here](http://hacktoberfest.digitalocean.com) and submit your pull requests after Oct 1st if you would like it to count for the official Hacktoberfest swag.

**Comment by Smalloow** [comment]
I can take this one

**Comment by crweiner** [comment]
> I can take this one

I'd prefer one PR per person in order to allow the most people to earn their swag as possible, please.

**Comment by Smalloow** [comment]
Sure thing, I'll redact the first one

**Comment by gmlunesa** [comment]
Hi @crweiner, can I take this one? Thank you~

**Comment by crweiner** [comment]
Yes, anyone can take this one! I'd love to get them added today!

**Comment by akshgpt7** [comment]
@crweiner Is this issue still up for grabs?

**Comment by crweiner** [comment]
Added in PR #95
