### ISSUE TITLE
Setup Social Cards - MkDocs Material

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#545]
A good first issue to tackle for Hacktoberfest! 🎃 

This site is now a MkDocs site running the material theme. However, the social cards either show old info from 2021, or no info at all. [Following this setup guide](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/), it would be nice to setup working social cards for this new site!

The Hacktoberfest Swag List is deployed via Netlify, so please be sure all dependencies are committed so they can be parsed by Netlify. 👍

**Comment by Asmit2952** [comment]
Can I work on this?

**Comment by crweiner** [comment]
Of course, @Asmit2952! I don't assign Issues to just one person, as I have found that many times they don't follow through. You're more than welcome to submit a PR and reference this Issue number. 👍

**Comment by Asmit2952** [comment]
Okay cool. I'll be happy to work on this. If I get any doubts, I'll ping you here :)
