### ISSUE TITLE
Add a favicon.ico to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#547]
Welcome to another fun Hacktoberfest, everyone! This year, the Hacktoberfest Swag List has been re-written to MkDocs and themed by the [Material theme](https://squidfunk.github.io/mkdocs-material/).

As an easy first issue for someone who hasn't participated before, please [follow this guide to add a favicon.ico to the Swag List website](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/?h=favicon). Please upload the favicon.ico file to the `/docs/img/` directory and point to the proper location in the `mkdocs.yml` file.

Official Hacktoberfest brand assets can [be found here](https://hacktoberfest.com/_next/static/media/event-kit.4f2bab5f.zip) to pick one to convert into a favicon.

Happy Hacktoberfest all! 🎃 🍂

**Comment by neutr0n420** [comment]
Hey I would love to contribute to this issue can you assign it to me?

**Comment by shittusaheed01** [comment]
Hi, I'm interested in this issue and I would love to be assigned to it

**Comment by GulamMd** [comment]
Hello I am also new can you assign this to me i want to learn how these things work. Thanks in advance
