### ISSUE TITLE
Add Accord Project to the 2019 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#55]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://github.com/crweiner/hacktoberfest-swag-list/issues/44#issuecomment-535578259), [Accord Project](https://www.accordproject.org/) is participating in Hacktoberfest 2019 by giving away their own swag.

Please add Accord Project to the 2019 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file. 

You will need to locate a blog post (or official tweet), the type of swag being offered, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to [register for Hacktoberest first by clicking here](http://hacktoberfest.digitalocean.com) and submit your pull requests after Oct 1st if you would like it to count for the official Hacktoberfest swag.

**Comment by crweiner** [comment]
Being worked on in PR #49, but presently incomplete.

**Comment by oorjitchowdhary** [comment]
can i take this up?

**Comment by crweiner** [comment]
@oorjitchowdhary Yes indeed, you're certainly welcome to if you think you can complete it relatively soon! :+1:
