### ISSUE TITLE
Add Hasura to the 2022 Hacktoberfest Swag List!

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#554]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://hasura.io/blog/hasura-joins-hacktoberfest-3rd-year-in-a-row/), Hasura is participating in Hacktoberfest 2022 by giving away their own swag. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by sdeepanshu17** [comment]
Please assign this to me.

**Comment by gaurang7goel** [comment]
Hi, can you assign me this issue.

**Comment by letsintegreat** [comment]
Hey @crweiner! I would like to work on this issue.
