### ISSUE TITLE
Add Medusa to the 2022 Hacktoberfest Swag List!

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#556]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://medusajs.com/blog/medusa-hackathon), MedusaJS is participating in Hacktoberfest 2022 by giving away their own swag. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by smeet07** [comment]
#566 this PR solves this issue

**Comment by letsintegreat** [comment]
@crweiner As #566 has been merged, kindly close this issue so that newcomers don't get attracted to this issue?

**Comment by crweiner** [comment]
Thank you, solved in #566. 🎉
