### ISSUE TITLE
Add MindsDB to the 2022 Hacktoberfest Swag List!

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#557]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://mindsdb.com/hacktoberfest/), MindsDB is participating in Hacktoberfest 2022 by giving away their own swag. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by amitmishra11** [comment]
Please assign this issue to me

**Comment by amitmishra11** [comment]
@crweiner I have made a PR for this issue please see

**Comment by crweiner** [comment]
Minds DB has been added in PR #582
