### ISSUE TITLE
Add Speckle to the 2022 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#558]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://speckle.community/t/hacktoberfest-2022-with-speckle/3641), Speckle is participating in Hacktoberfest 2022 by giving away their own swag. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by vikash485** [comment]
Hello @crweiner, I have made a pull request for this issue. Please verify the same. Thanks a lot

**Comment by Csrivastava003** [comment]
I would like to work on this issue

**Comment by chiragchandnani10** [comment]
#584  This PR completes this issue. Can you assign hacktoberfest-completed tag to this? Thanks!

**Comment by crweiner** [comment]
Speckle added in PR #560.
