### ISSUE TITLE
Add ToolJet to the 2022 Hacktoberfest Swag List!

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#559]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://blog.tooljet.com/hacktoberfest-2022/), ToolJet is participating in Hacktoberfest 2022 by giving away their own swag. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by Sidd2024** [comment]
hey there I would love to work on this issue, please assign it to me!

**Comment by crweiner** [comment]
Hi @Sidd2024! 👋 Issues are never assigned, all PRs are first-come-first-served. I've seen over the years that assigned Issues tend not to be completed, so I don't assign them anymore. 👍

**Comment by Sidd2024** [comment]
okay no problem, I'll raise a pr directly!👍🏻

**Comment by Sidd2024** [comment]
here, please review it #565

**Comment by crweiner** [comment]
Added in #565
