### ISSUE TITLE
Add Operation Code to the 2019 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#56]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://github.com/crweiner/hacktoberfest-swag-list/issues/44#issuecomment-535691674), [Operation Code](https://github.com/OperationCode) is participating in Hacktoberfest 2019 by giving away their own swag.

Please add Operation Code to the 2019 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file. 

You will need to locate a blog post (or official tweet), the type of swag being offered, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to [register for Hacktoberest first by clicking here](http://hacktoberfest.digitalocean.com) and submit your pull requests after Oct 1st if you would like it to count for the official Hacktoberfest swag.

**Comment by PatrickRNG** [comment]
Hello! can i work on this one?

**Comment by crweiner** [comment]
If Hacktoberfest has already started in your time zone and contributing now will count towards the official swag for you, then feel free! But please only take 1 from the list to provide others a chance to earn some meaningful PRs as well. Thank you!

**Comment by PatrickRNG** [comment]
@crweiner Sure thing! I will make the PR tomorrow!

**Comment by crweiner** [comment]
I actually think that PRs are currently counting because it's already Oct 1st in Japan/Korea/Australia/New Zealand, etc. You can submit your PR and check your [Hacktoberfest Profile](https://hacktoberfest.digitalocean.com/profile) to see if it shows up there (I have no idea how long it takes to appear),

**Comment by crweiner** [comment]
Added in PR #96
