### ISSUE TITLE
Add TON to the 2022 Hacktoberfest Swag List!

### ISSUE THREAD

**Issue by moingshaikh** [crweiner/hacktoberfest-swag-list#562]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://www.tonspace.co/hacktonberfest/), TON is participating in Hacktoberfest 2022 by giving away their own swag. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by Sidd2024** [comment]
hello, @moingshaikh I would like to work on this issue, please assign it to me.

**Comment by moingshaikh** [comment]
> hello, @moingshaikh I would like to work on this issue, please assign it to me.

Feel free to work on it. 

Please see the Contributing Guidelines [here](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) and start your Hacktoberfest journey :)

**Comment by crweiner** [comment]
Hi @moingshaikh. While I appreciate your zeal, and you certainly have a knack for copy-and-pasting, what swag is TON offering for people's meaningful contributions? Is it an NFT? I'll have to consider if that goes along with my goal for this project... 😐

**Comment by moingshaikh** [comment]
Hi Chandler,

Yes, they are offering some limited Hacktober Fest Edition NFT.

I agree with you about consideration. My apologies for being too quick on
this 😑

**Comment by crweiner** [comment]
I appreciate you letting us know about TON's offering for this Hacktoberfest. Personally, I have some pretty negative feelings towards NFTs and don't really consider this to be swag. It's an odd grey area...

I'll close this Issue for now, but I'm not 100% ruling it out. I'll have to see what others think.

Thank you again! 👍
