### ISSUE TITLE
Feature: Make all off-site links open in a new tab

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#563]
MkDocs and the Material theme have support for Python Markdown. To get off-site links to open in a new tab, instead of inline at HacktoberfestSwagList.com, they must be given the `target="_blank"` attribute. 

Please enable the [Attribute Lists](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#admonition) extension so that this can then be added to each off-site link.

[This PR](https://github.com/squidfunk/mkdocs-material/discussions/3660) and [this PR](https://github.com/mkdocs/mkdocs/issues/1958) and [this PR](https://github.com/squidfunk/mkdocs-material/issues/1609) will lead you down the right path. 😄

**Comment by rrsingh11** [comment]
Hello, Can you please assign this issue to me?

**Comment by donheshanthaka** [comment]
Hey there, can i work on this too

**Comment by asi309** [comment]
#573 Enables Attributes List extension

**Comment by crweiner** [comment]
Hello all! I don't assign issues, as I have seen that more often than not, people tend to disappear once assigned. 

This Issue has not yet been fully resolved, and I welcome additional PRs!

**Comment by crweiner** [comment]
Featured added in #573, but all of the links still need to be updated across the Swag List. 

Additionally, the Contributing.md doc should be updated with the reference too. 👍
