### ISSUE TITLE
Add Hasura to the 2019 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#57]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://github.com/crweiner/hacktoberfest-swag-list/issues/44#issuecomment-535993209), [Hasura](https://hasura.io) is participating in Hacktoberfest 2019 by giving away their own swag.

Please add Hasura to the 2019 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file. 

You will need to locate a blog post (or official tweet), the type of swag being offered, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to [register for Hacktoberest first by clicking here](http://hacktoberfest.digitalocean.com) and submit your pull requests after Oct 1st if you would like it to count for the official Hacktoberfest swag.

**Comment by moingshaikh** [comment]
If no one has taken it, I'm ready to take up.

**Comment by cendekia** [comment]
let me take it please

**Comment by crweiner** [comment]
I actually think that PRs are currently counting because it's already Oct 1st in Japan/Korea/Australia/New Zealand, etc. You can submit your PR and check your [Hacktoberfest Profile](https://hacktoberfest.digitalocean.com/profile) to see if it shows up there (I have no idea how long it takes to appear),

**Comment by crweiner** [comment]
Being worked on in #69

**Comment by crweiner** [comment]
Added in #69
