### ISSUE TITLE
Add Novu to the 2022 Hacktoberfest Swag List!

### ISSUE THREAD

**Issue by Rutam21** [crweiner/hacktoberfest-swag-list#578]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://github.com/novuhq/novu#readme), Novu is participating in Hacktoberfest 2022 by giving away their own swag. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by Rutam21** [comment]
@crweiner Please assign this to me. I will raise a PR soon. Thanks

**Comment by crweiner** [comment]
Hello @Rutam21! 👋 I don't assign Issues, but feel free to submit a PR! 👍

**Comment by Asmit2952** [comment]
Hey @crweiner this repository seems to be excluded from hacktoberfest. Is there any way we can undo that?

**Comment by crweiner** [comment]
Humm...thank you for letting me know, I'll reach out.

**Comment by Sidd2024** [comment]
Yeah @Asmit2952 you are right..

**Comment by crweiner** [comment]
I'm working on it. 👍 Going through the official channels, I hope to have it resolved soon.

**Comment by crweiner** [comment]
Hey @Asmit2952, can you please take another look? I reached out to the Hacktoberfest team and they let me know they lifted the exclusion. 😺

**Comment by Sidd2024** [comment]
@crweiner yeah I've checked and the repo is included again ✨

**Comment by Asmit2952** [comment]
> Hey @Asmit2952, can you please take another look? I reached out to the Hacktoberfest team and they let me know they lifted the exclusion. 😺

Yes @crweiner the repository is now a part of hacktoberfest!
