### ISSUE TITLE
Add Parity (Substrate?) to the 2019 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#58]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://github.com/crweiner/hacktoberfest-swag-list/issues/44#issuecomment-536203438), [Parity](https://www.parity.io) (or perhaps their sister community of [Substrate](https://substrate.dev/)?) is participating in Hacktoberfest 2019 by giving away their own swag.

Please add Parity/Substrate to the 2019 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file (once you figure out what is the correct title/company to list). 

You will need to locate a blog post (or official tweet), the type of swag being offered, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to [register for Hacktoberest first by clicking here](http://hacktoberfest.digitalocean.com) and submit your pull requests after Oct 1st if you would like it to count for the official Hacktoberfest swag.

**Comment by moingshaikh** [comment]
I've just verified with their official blog, they're participating in Hacktoberfest 2019. https://www.parity.io/hacktoberfest-2019-parity/)

I'm taking this issue :)

**Comment by crweiner** [comment]
I'd prefer one PR per person in order to allow the most people to earn their swag as possible, please.

**Comment by moingshaikh** [comment]
> I'd prefer one PR per person in order to allow the most people to earn their swag as possible, please.

I agree with that. In fact, I appreciate your approach. Thanks for clarifying. I appreciate your efforts in spreading Hacktoberfest to everyone. I'll make sure I take only one issue and thus contribute one PR to this repo to let others work on this.

**Comment by crweiner** [comment]
Thanks for understanding @moingshaikh! You're certainly welcome to fix typos, CodeClimate/markdown formatting, alphabetizing, adding features, etc, so you're not limited to just 1 PR _total_, I'd just like to give a chance for others to add new companies to the list as well.

**Comment by Tuxhedoh** [comment]
@moingshaikh  do you have another one. If you do, I don't mind claiming this one. I'll get it staged to make PR tomorrow.

**Comment by crweiner** [comment]
I actually think that PRs are currently counting because it's already Oct 1st in Japan/Korea/Australia/New Zealand, etc. You can submit your PR and check your [Hacktoberfest Profile](https://hacktoberfest.digitalocean.com/profile) to see if it shows up there (I have no idea how long it takes to appear),

**Comment by moingshaikh** [comment]
> @moingshaikh do you have another one. If you do, I don't mind claiming this one. I'll get it staged to make PR tomorrow.

Don't worry, feel free to take it.

**Comment by crweiner** [comment]
Added in #71
