### ISSUE TITLE
Compromise in the alphabetical order in list.md

### ISSUE THREAD

**Issue by letsintegreat** [crweiner/hacktoberfest-swag-list#580]
Apparently an organization with initial "T" (ToolJet) has been put after an organization having initial "U" (UnionML), thus compromising the alphabetical order. This needs to be fixed by placing the organizations in the correct order.

**Comment by crweiner** [comment]
Ahh, yep, this happened due to the amount of PRs I merged all at once. thank you for catching this. Please submit a PR for the fix. 👍 

Working on reviewing #577 now, so I don't want to step on your toes again. 😅 

Appreciate it!
