### ISSUE TITLE
Add opsdroid to the 2019 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#59]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://github.com/crweiner/hacktoberfest-swag-list/issues/44#issuecomment-536338558), [opsdroid](https://opsdroid.dev/) is participating in Hacktoberfest 2019 by giving away their own swag.

Please add opsdroid to the 2019 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file. 

You will need to locate a blog post (or official tweet), the type of swag being offered, and a link to their signup form (or some info on how they are tracking contributors). 

Be sure to [register for Hacktoberest first by clicking here](http://hacktoberfest.digitalocean.com) and submit your pull requests after Oct 1st if you would like it to count for the official Hacktoberfest swag.

**Comment by moingshaikh** [comment]
If this issue is available, I can take it.

**Comment by crweiner** [comment]
If Hacktoberfest has already started in your time zone and contributing now will count towards the official swag for you, then feel free! But please only take 1 from the list to provide others a chance to earn some meaningful PRs as well. Thank you!

**Comment by crweiner** [comment]
I actually think that PRs are currently counting because it's already Oct 1st in Japan/Korea/Australia/New Zealand, etc. You can submit your PR and check your [Hacktoberfest Profile](https://hacktoberfest.digitalocean.com/profile) to see if it shows up there (I have no idea how long it takes to appear),

**Comment by moingshaikh** [comment]
Yes. I am working on this now :)

**Comment by mohatagarvit** [comment]
#72 I have submitted this PR for this issue but I am not able to remove 2 of the lint errors. Can someone help me in figuring out where they are occurring.

**Comment by crweiner** [comment]
> #72 I have submitted this PR for this issue but I am not able to remove 2 of the lint errors. Can someone help me in figuring out where they are occurring.

Hay @mohatagarvit, you can read up about [that error here](https://codeclimate.com/github/crweiner/hacktoberfest-swag-list/pull/72#readup-5d9255d981dfa70001000023), but in all honesty, we can just make this simpler and reference the blog post per my [comment here](https://github.com/crweiner/hacktoberfest-swag-list/pull/72#issuecomment-536746782). That saves on the headache. :smile:

**Comment by crweiner** [comment]
Added in #72
