### ISSUE TITLE
Add LocalStack to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#591]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://localstack.cloud/blog/2022-10-01-contribute-to-open-source-with-localstack-hacktoberfest/), LocalStack is participating in Hacktoberfest 2022 by giving away their own swag for meaningful contributions. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by Arnav-Negi** [comment]
Hi, I would love to work on this please assign it to me!

**Comment by crweiner** [comment]
Added in PR #593
