### ISSUE TITLE
Company Github Repo Links

### ISSUE THREAD

**Issue by AbhishekTiwari23** [crweiner/hacktoberfest-swag-list#596]
Hello, I want to contribute to this project. I found that the GitHub repository link of most of the companies is not attached. I want to add these links as it will help the contributor react to the repo in just a single click

**Comment by crweiner** [comment]
I want to make sure that people are purposely reading the contents on the Swag List and not just clicking on a GitHub URL and spamming them. Some organizations on the List have their repos included if they are specifically called out in that company's blog posts/tweets. If you feel like updates are needed to any company on the list, please submit a PR so I can review it! 😄 However, I'm not looking to add a line item like ```- Repo:``` as a required field on the list.

Hope that helps! Happy Hacktoberfest! 🎃

**Comment by AbhishekTiwari23** [comment]
> I want to make sure that people are purposely reading the contents on the Swag List and not just clicking on a GitHub URL and spamming them. Some organizations on the List have their repos included if they are specifically called out in that company's blog posts/tweets. If you feel like updates are needed to any company on the list, please submit a PR so I can review it! 😄 However, I'm not looking to add a line item like `- Repo:` as a required field on the list.
> 
> Hope that helps! Happy Hacktoberfest! 🎃

Thanks, @crweiner, for guiding me. And if I can contribute then please let me know. Thanks once again.

**Comment by crweiner** [comment]
I'm always up for revieiwing good, meaningful, helpful PRs, @AbhishekTiwari23! 

If you're new to Hacktoberfest and/or open source projects, I'd reccommend reviewing the [Resources for Beginners guide on the Hacktoberfest website](https://hacktoberfest.com/participation/#beginner-resources). That section, along with everything on the [Participation page](https://hacktoberfest.com/participation/#beginner-resources), may be very useful to you!
