### ISSUE TITLE
Add Space Jelly and Cloudinary to the 2022 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#601]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://spacejelly.dev/hacktoberfest/), Space Jelly and Cloudinary are participating in Hacktoberfest 2022 by giving away their own swag for meaningful contributions. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by AbhishekTiwari23** [comment]
@crweiner, I want to do this. Please allow me.

**Comment by crweiner** [comment]
Added in PR #605
