### ISSUE TITLE
Add Docker to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#603]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://docker.github.io/hacktoberfest/), Docker is not only sponsoring Hacktoberfest 2022 as a whole, but is also participating by giving away their own swag for meaningful contributions. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by AbhishekTiwari23** [comment]
Hello @crweiner, I checked out that swags are still not announced by docker. But I want to do this once announced.

**Comment by Aishubalaji** [comment]
Hello @crweiner, I would love to do the changes as soon as swags are announced by docker
