### ISSUE TITLE
Add Uno Platform Back to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#611]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://platform.uno/blog/uno-platform-at-hacktoberfest-2022-prizes-and-how-to-participate/), Uno Platform is returning for Hacktoberfest 2022 by giving away their own swag for meaningful contributions. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by deepesh16b** [comment]
please assign this to me

**Comment by kev-odin** [comment]
Check PR #613

**Comment by crweiner** [comment]
Uno was addded in PR #613
