### ISSUE TITLE
Add Airbyte to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#614]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://airbyte.com/connector-contest), Airbyte is celebrating Hacktoberfest 2022 by giving away their own swag for meaningful contributions. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by riyaku11** [comment]
@crweiner  please assign me this

**Comment by Vedant755** [comment]
Hey! I have done the PR on the issue which is added the Airbyte to the hacktoberfest swag list. #627 
Thanks for this repo!
