### ISSUE TITLE
Add ClueLess to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#615]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://www.clueless.tech/hacktoberfest), ClueLess is participating in Hacktoberfest 2022 by giving away their own swag for meaningful contributions. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by alpesh-rama** [comment]
Please assign me to this issue. Thank you

**Comment by crweiner** [comment]
Hi @alpesh-rama! Issues are not assigned, it's first-come-first-served for a good PR. 👍
