### ISSUE TITLE
Add OpenSearch to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#617]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://www.opensearch.org/blog/community/2022/10/hacktoberfest-2022/), OpenSearch is joining in on the Hacktoberfest fun for the first time by giving away their own swag for meaningful contributions. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by Mr-DJ** [comment]
please assign this to me, thanks :)

**Comment by Mr-DJ** [comment]
submitted a pr 🎉

**Comment by Mr-DJ** [comment]
#623
