### ISSUE TITLE
Add LambdaTest to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#618]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://www.lambdatest.com/blog/celebrate-hacktoberfest-2022-with-lambdatest/), LambdaTest is joining in on the Hacktoberfest fun by giving away their own swag for meaningful contributions. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by Utkarsh212** [comment]
Please assign this to me so that I could work upon it

**Comment by crweiner** [comment]
Hi @Utkarsh212, I do not typically assign Issues to one person. All meaningful PRs are considered first-come-first-served. 👍

**Comment by Utkarsh212** [comment]
@crweiner Added LambdaTest to list.md. Refer PR: #621

**Comment by crweiner** [comment]
Added via #621
