### ISSUE TITLE
Add RapidAI to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#619]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://rapidapi.com/learn/hacktoberfest), RapidAI is joining in on the Hacktoberfest fun by giving away their own swag for meaningful contributions. 😄 They're even sponsoring (or somehow taking part) in the offical Hacktoberfest celebration and swag!

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by SainathPoojary** [comment]
Hey @crweiner, I want to work on this. Please assign it to me.

**Comment by elenajp** [comment]
Hi @crweiner I would also love to contribute :)

**Comment by PinetheApple** [comment]
Hello, I added it to the list here - [#628](https://github.com/crweiner/hacktoberfest-swag-list/pull/628#issue-1397862033)
