### ISSUE TITLE
Add Bagisto to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#629]
Bagisto is giving cool Bagisto swag pack for every 4 accepted PRs. 
The swag pack includes a plus Bagisto Elephant, stickers, t-shirt, pen and notebook! 

More details available [here](https://webkul.com/meetups/hacktober-fest-bagisto-2022/)

This issue is open for anyone who wants to contribute to this repo. 

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting before submitting a PR.

**Comment by crweiner** [comment]
Hey @vimode! 👋 Nice to see you over here too! 😄 

Bagisto was added in PR #546 [and is currently on the site](https://hacktoberfestswaglist.com/list/#bagisto). ❤️  I'll close this Issue, but please do feel free to raise any others and/or submit PRs!
