### ISSUE TITLE
Add Gita to the  Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#630]
[The Gita Initiative](https://github.com/gita) giving a hardcopy of The Bhagavad Gita and stickers for 4 or more accepted PRs

More details available [here](https://www.linkedin.com/posts/vedvyas_github-gitagita-bhagavad-gita-in-json-activity-6982314384161140736-o370)

This issue is open for anyone who wants to contribute to this repo. 

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting before submitting a PR.

**Comment by crweiner** [comment]
Gita added in #633
