### ISSUE TITLE
Add steps to build the site 

### ISSUE THREAD

**Issue by Asmit2952** [crweiner/hacktoberfest-swag-list#635]
Hey @crweiner as I was working on previous issue, I had to setup the site locally. I had no knowledge of how to set it up, so had to dig in to many resources and head to StackOverflow as well. 

I would like to add setup steps in contributing.md file if you think this is a good addition.

**Comment by crweiner** [comment]
Yes indeed! I think that's a great addition. 👍 Feel free to submit a PR adding setting up a local environment in Contributing.md.

**Comment by Vishwa-docs** [comment]
Hey, can you give me some more information on this issue?

I can write the steps in contributions.md on how to fork, clone etc. Is that enough or are there any other steps that need to be added?

**Comment by Asmit2952** [comment]
> Hey, can you give me some more information on this issue?
> 
> I can write the steps in contributions.md on how to fork, clone etc. Is that enough or are there any other steps that need to be added?

Hey, I have submitted a PR already.
