### ISSUE TITLE
 Add SuiteCRM to the Hacktoberfest Swag List  

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#637]
[SuiteCRM](https://suitecrm.com/) are looking for contributions in their three open source repositories; [SuiteCRM](https://github.com/salesagility/SuiteCRM), [SuiteDocs](https://github.com/salesagility/SuiteDocs), and [SuiteCRM-Core](https://github.com/salesagility/SuiteCRM-Core), valid contributions will be rewarded with exclusive swag, such as T-shirts, stickers, and possibly even a SuiteCRM-branded mug!

More details available [here](https://community.suitecrm.com/t/hacktoberfest-2022/86484)

This issue is open for anyone who wants to contribute to this repo. 

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully accepted.

**Comment by Sidd2024** [comment]
hello @vimode I've raised a PR #639 , please review and add labels😇

**Comment by vimode** [comment]
Hello @Sidd2024 thanks for your contribution. But I am not a maintainer just a contributor like you. 

The maintainers have other PRs in the pipeline it seems so please be patient, the necessary changes will be done and valid PRs will be merged

**Comment by crweiner** [comment]
Yes indeed, thank you @vimode for making the Issue and I'm a one-man-band here @Sidd2024. 😅 Working through the PRs right now. 👍

**Comment by crweiner** [comment]
Added in PR #642
