### ISSUE TITLE
Change Octocat Background to Purple

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#64]
This is a great first issue for those new to Hacktoberfest and coding in general!

This swag list is a Jekyll site that uses a basic HTML template to build its pages. Part of that template is putting the little Octocat logo in the top-right corner so people browsing the website can very easily jump to the GitHub repo.

I am looking for someone to change the hex color value for the background of the Octocat from orange to purple to match the official color scheme of this year's Hacktoberfest theme.

You can find that file here: https://github.com/crweiner/hacktoberfest-swag-list/blob/master/_layouts/default.html

Please find where the Octocat portion of the template is and change the background color to something purple.

Once you have done that, submit a PR and view the preview that is generated automatically by Netlify to make sure it looks the way you want.

Thanks!

**Comment by mohatagarvit** [comment]
Hi, I am Garvit. I am new to Hacktoberfest and would like to contribute to solve this first issue.

**Comment by crweiner** [comment]
Closed in #68
