### ISSUE TITLE
Add StepZen to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#640]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://stepzen.com/blog/stepzen-hacktoberfest-2022), StepZen is returning for Hacktoberfest 2022 by giving away their own swag for meaningful contributions. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by priyanshu6781** [comment]
Hey, I want to work. Could you please assign this to me.

**Comment by crweiner** [comment]
[Issues are never assigned](https://hacktoberfestswaglist.com/contributing/#other-contributing-guidelines), first come, first served for a meaningful PR. 👍

**Comment by RUPAAK** [comment]
@crweiner which file should I look for ?

**Comment by RUPAAK** [comment]
@crweiner  I have created the PR
