### ISSUE TITLE
UI update suggestion : Title hierarcy update

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#641]
Hello, 

I noticed the hierarchy for the title/name of the company and the bold particulars below look very similar. 
I think it would look better and more distinguishable with a little change in the Header levels. 🎚️ 

Suggestion : The legends be changed to with Header Level 2 and titles with Header Level 3. 
This might screw up your current hierarchy a bit maybe, as the title of the whole section *A to Z Order of Companies* and the legends will share the same level. 😄 

Attached a screenshot to clarify 👀 
![hierarchy-A](https://user-images.githubusercontent.com/39148877/194349023-cfcbf0fa-1416-40ed-8a0e-da4b7aaa5e6c.png)

Thank you.

**Comment by crweiner** [comment]
Currently being tested in [header-test branch](https://github.com/crweiner/hacktoberfest-swag-list/tree/header-test).

**Comment by crweiner** [comment]
Will revisit this for Hacktoberfest 2023, closing this prior issue for now.
