### ISSUE TITLE
Add Neo4j to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#647]
[Neo4j](https://suitecrm.com/) are looking for contributions for all [Neo4j Projects](https://github.com/search?l=&o=desc&q=neo4j&s=&type=Repositories), valid contributions stand a chance to win a Pixoo display. 

More details available [here](https://medium.com/neo4j/hacktoberfest-at-neo4j-9991ccc98c33)

This issue is open for anyone who wants to contribute to this repo. 

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by crweiner** [comment]
![cat nice](https://media.giphy.com/media/xu3nTl5OdCuqs/giphy.gif)
