### ISSUE TITLE
Add Globo to the Hacktoberfest Swag List (translation required)

### ISSUE THREAD

**Issue by kev-odin** [crweiner/hacktoberfest-swag-list#648]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://hacktoberfest.globo.com/), Globo is participating for Hacktoberfest 2022 by giving away swag for meaningful contributions. smile

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by crweiner** [comment]
Thanks @kev-odin! Happy to see Globo back for another year! If memory serves, this organization has a shipping limitation to consider, as they don't send their swag worldwide. Let's see if either I am wrong or someone can find it! 😆
