### ISSUE TITLE
Add NativeScript to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#649]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://twitter.com/NativeScript/status/1577660072150196224), NativeScript is joining in on the Hacktoberfest by giving away their own swag for meaningful contributions. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by akk312000** [comment]
Can I take this one?

**Comment by kev-odin** [comment]
Go for it! First come, first serve. Just be sure to read the [CONTRIBUTING.md file](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

**Comment by akk312000** [comment]
Thanks @kev-odin , sure would read CONTRIBUTING.md file as you instructed

**Comment by crweiner** [comment]
Added in #651
