### ISSUE TITLE
Add webkul to hacktoberfest-swag-list

### ISSUE THREAD

**Issue by naksh2004** [crweiner/hacktoberfest-swag-list#654]

**Comment by vimode** [comment]
Thanks for your opening this issue.
Webkul's Bagisto is already added to the list in #567 
https://hacktoberfestswaglist.com/list/#bagisto

**Comment by crweiner** [comment]
Hey @naksh2004! 👋 As @vimode pointed out, this is already on the swag list under the name of the project, Bigisto. That's how I typically like to do things around here, for clarity sake. Thank you though, happy Hacktoberfest! 🎃
