### ISSUE TITLE
Add OpenReplay to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#655]
[OpenReplay](https://openreplay.com/) are looking for contributions to beginner friendly issues at their [repo](https://github.com/openreplay/openreplay) to help beginners get their first PR. 1️⃣ 

If you contribute towards custom plugins and custom heuristics, you stand a chance to win $50 Amazon Gift Card. 🎁 

More details available [here](https://blog.openreplay.com/its-hacktoberfest-and-were-here-for-it/) 

This issue is open for anyone who wants to contribute to this repo. 

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by Ruchika30** [comment]
Hi @crweiner . I would like to take this up
