### ISSUE TITLE
Add Devtron to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#656]
⭐ [Devtron](https://devtron.ai/), one of the official supporters of Hacktoberfest are looking for contributions towards their community charts, docker templates and documentation.  At this point the goodies and giveaways are not revealed. 

They are also running multiple events like micro blogging, bug hunt, devtron art and twitter threads throughout the month which will have separate prizes. 🏆 

More details available [here](https://github.com/devtron-labs/hacktoberfest2022) 

This issue is open for anyone who wants to contribute to this repo. 

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by Ruchika30** [comment]
Hi @crweiner . I would like to take this up

**Comment by vimode** [comment]
Hey @Ruchika30,  Issues are not assigned, please read the contributing guidelines for more info.
