### ISSUE TITLE
Add Modtoberfest to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#657]
[Modtoberfest](https://modtoberfest.com/) is an annual celebration of open source projects in the Minecraft community. 🎮 

Make valid pull requests to at least four different [participating projects](https://modtoberfest.com/repositories) to be eligible to receive a prize pack which includes stickers and pins! 🎁 

They will also [plant 1 tree](https://modtoberfest.com/modtoberforest) for each valid PR submitted in this event, up to 1000 trees! 🌲 

This issue is open for anyone who wants to contribute to this repo. 

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by vimode** [comment]
@crweiner  This is a parallel event alongside hacktoberfest. But since most projects in the list of repos are also tagged `hacktoberfest`, contributing to those will count towards Hacktoberfest. 

I think with a note that repos tagged with `hacktoberfest` will count towards Hacktoberfest but contributing to other repos as well will help you win those prizes should be enough as the list of participating Minecraft projects is amazingly long! 📜 ✨ 

You opinions, should this be added to the list?

**Comment by crweiner** [comment]
Yes, absolutely! Like you said, many repos are opted-in to Hacktobefest, I like that they have a good [set of rules](https://modtoberfest.com/rules), they're clearly modeling this after Hacktoberfest, there's a [huge list of participating repos](https://modtoberfest.com/repositories) and Minecraft has been a _fantastic_ way to get people interested in coding/modding/hacking. Excellent find! 🥇
