### ISSUE TITLE
Add AppFlowy to the hacktoberfest swag list

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#686]
[AppFlowy](https://www.appflowy.io/) is a popular open source alternative to Notion built with Flutter and Rust.

If your PR is accepted and it fixes a bug, adds functionality or makes the codebase easier to use or understand you get a [special Contributor T-shirt.](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/contributing-to-appflowy#contributor-t-shirt) 

This swag promotion is not limited to hacktoberfest event but is available all year long. 
They are also participating in the hacktoberfest event so PRs will also be counted towards your hacktoberfest total too.

**Comment by crweiner** [comment]
Hey @vimode! 👋 Sorry for the silence here the last few days; life had gotten in the way! 

I am looking for organizations going over and above for Hacktoberfest by offering their own, unique swag for contributions during the holiday. So, I don't think that organizations like AppFlowy would fit, exactly. Similar things have come up with organizations like Kong in years past. I usually direct people over [here at DevSwag.io](https://github.com/swapagarwal/swag-for-dev), but it looks like that project may be abandoned. 😐 

I'm reviewing your PR and will make changes as necessary, no worries, and thank you again for all your help this year for the Hacktoberfest Swag List!

**Comment by vimode** [comment]
Hey @crweiner  That's all right. I hope everything is okay. 

I understand, as you might have read from my messages in the PR I too wasn't sure if AppFlowy be considered in the same group as Kong or not.

> I am looking for organizations going over and above for Hacktoberfest by offering their own, unique swag for contributions during the holiday. 

This explanation makes the clear distinction. 

Thanks for fixing the PR.
