### ISSUE TITLE
Add Gatsby To List?

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#7]
Hello all!

I wanted to see the community's thoughts regarding adding Gatsby to the list. They give out [free swag](https://www.gatsbyjs.org/docs/contributor-swag/) to all of their contributors all the time, not just during Hacktoberfest, yet they do have a [blog post talking about Hacktoberfest](https://www.gatsbyjs.org/blog/2018-10-09-hacktoberfest-kickoff/) this year.

Would you want companies like this to be added to the Hacktoberfest Swag List, or just stick to those companies that specifically celebrate Hacktoberfest?

If you think they should be included, write it up and submit a PR! :+1:

**Comment by gagandeepp** [comment]
Sounds good , I just got my T-shirt a few days back

**Comment by crweiner** [comment]
I'm more inclined to promote companies that offer unique swag for specifically Hacktoberfest rather than year round in this little project. That's why I closed this issue a while ago.

Please let me know if you see a post from Gatsby encouraging participation in Hacktoberfest 2019 and/or offering unique swag just for the holiday. 

Otherwise, I think that it's best suited for [devswag.io](https://devswag.io)
