### ISSUE TITLE
Verify Companies for Hacktoberfest 2023 Participation - Setup The Hacktoberfest Swag List for 2023

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#710]
Hacktoberfest 2023 is right around the corner! Time to get this repo in tip-top shape to prepare!

Current Hacktoberfest news includes:
* [Celebrating ten years of Hacktoberfest!](https://www.digitalocean.com/blog/ten-years-hacktoberfest)
* [Hacktoberfest and Microsoft Learn](https://learn.microsoft.com/en-us/contribute/content/hacktoberfest)

Please make commits to the [prepare-for-2023 branch](https://github.com/crweiner/hacktoberfest-swag-list/tree/prepare-for-2023), see #711

**Comment by crweiner** [comment]
If you know of any companies offering unique swag as a reward for helping during Hacktoberfest, please leave their info below!

Remember:

- This website/repo is not about collecting all of the swag you can. 
- It is about the open-source community and highlighting organizations that purposely want to drive traffic to their projects during Hacktoberfest by offering unique swag.
- Swag is an added benefit of helping out these awesome organizations, not the reason for you to contribute in the first place.
- Participating in Hacktoberfest requires following the [official values](https://hacktoberfest.com/participation/#values), including [not spamming the participating companies](https://hacktoberfest.com/participation/#spam).

**Comment by vimode** [comment]
Hey @crweiner I am back! 😄 
Great work prepping the hacktoberfestswaglist for 2023! Everything looks good, clean and ready for 2023! 🥳 

I see things have changed a bit, no more adding issues for new companies and instead this single issue thread? 
So should I *flood* this issue with the list of all the companies and respective links or just get on with making a single PR for all the ones I found?

**Comment by crweiner** [comment]
Hello @vimode! Good to see you again for another Hacktoberfest!

> I see things have changed a bit, no more adding issues for new companies and instead this single issue thread?

I started this one issue just to organize things back in August, but I didn't see many companies participating as of then. Going forward, anyone can raise an Issue to add a company to the list and a PR doing so! I'll close this Issue in particular so we can get back to doing it that way again!

> So should I flood this issue with the list of all the companies and respective links or just get on with making a single PR for all the ones I found?

If you could make a single PR for everything so far, that would be much easier for me to review today. 😄  Thank you very much for your contributions again this year!

**Comment by crweiner** [comment]
As above, now that Hacktoberfest is upon us, I'm closing this Issue in favor of creating new issues per organization just like #640.
