### ISSUE TITLE
Add Hanko.io to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#722]
[Hanko.io](https://www.hanko.io/hackathon) is participating in the Hacktoberfest 2023 with a Hackathon  with prizes which includes a Macbook Pro, Yubikey + other exclusive swag. 

They have also partnered with Hacktoberfest and Hacksquad, so your project will count towards hacksquad points too. 

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by crweiner** [comment]
Added in #733
