### ISSUE TITLE
Add MLH to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#723]
To celebrate Hacktoberfest, MLH is hosting [Global Open Source Week](https://events.mlh.io/events/9976-global-hack-week-open-source-week).

Complete [daily challenges](https://ghw.mlh.io/challenges) and attend events to earn points, Be in the top point earners to win swag like stickers, postcards and other swag. 

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by IshaanAdarsh** [comment]
@vimode i would like to work on this issue, can you assign it to me.

**Comment by vimode** [comment]
Hey @IshaanAdarsh these issues are open for everyone, so please go ahead make a PR for this.

**Comment by SparklinStar** [comment]
PR #727 created

**Comment by crweiner** [comment]
Thank you @vimode  and @SparklinStar! Added in [#727](https://github.com/crweiner/hacktoberfest-swag-list/pull/727)
