### ISSUE TITLE
Add Swirl to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#724]
[Swirl](https://swirl.today/contribute-to-swirl-this-hacktoberfest-2023/) is participating in the Hacktoberfest 2023.

Contribute with 4+ PRs or by create tutorials to win gift cards up to USD 100.

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by crweiner** [comment]
Added in #732
