### ISSUE TITLE
Add Otterize to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#725]
![Otterize Tweet](https://github.com/crweiner/hacktoberfest-swag-list/assets/39148877/b9366292-f396-419d-8327-28d5d13f108f)

Contribute to [Otterize](https://twitter.com/TheOtterize/status/1708516300270793003), earn swag by completing 3 successful PR/MRs

No other details provided at the moment.

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by SparklinStar** [comment]
PR #731

**Comment by crweiner** [comment]
Added in #731, thank you very much @vimode  and @SparklinStar!
