### ISSUE TITLE
Add Appsmith to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#735]
[Appsmith](https://community.appsmith.com/content/announcement/welcome-appsmith-hacktoberfest-2023) is participating in the Hacktoberfest 2023.

Create an Appsmith app in one of the 4 categories to win a swag pack.

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by AnTheMaker** [comment]
Added Appsmith in #758 758
