### ISSUE TITLE
Add Weaviate to The Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#738]
[Weaviate](https://weaviate.io/blog/hacktoberfest-2023) has announced their participation in the Hacktoberfest 2023. 

You can attend their workshops to learn more about it and get help to make your first contribution. The swags haven't been announced yet. 

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by Sugamgoel28** [comment]
Hello, I would like to work on this issue, I'm right on it.

**Comment by ikunal-04** [comment]
> Hello, I would like to work on this issue, I'm right on it.

Hye @Sugamgoel28 you're already quoted in another similar issue that you're working on that. So can you please let me take any one of the issue. It would be really great!

**Comment by Sugamgoel28** [comment]
Hey @ikunal-04, Sure, I'm done with this issue, however, you can start working on #772, I won't take it in that case. Happy Contributing!

**Comment by ikunal-04** [comment]
Thank you @Sugamgoel28 😊👍
