### ISSUE TITLE
Add Uno Platform to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#742]
[Uno platform](https://platform.uno/blog/hacktoberfest-2023-contributing-as-a-net-developer/) is participating in the Hacktoberfest 2023!

Make 2-9 quality PRs to win sweater, t-shirt, stickers and eBooks.

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by AdnanMuhib** [comment]
PR
- #744

**Comment by crweiner** [comment]
Thank you both! Added in #744
