### ISSUE TITLE
Add SEF to Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#747]
[SEF - Sustainable Education Foundation](https://sef.discourse.group/t/it-s-hacktoberfest-month/543) is giving t-shirts, stickers and exclusive coupons for your contributions to their projects.

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by crweiner** [comment]
I'm not certain if SEF is offering their own swag for Hacktoberfest, or mentioning that you _could_ win swag in general (they may not be aware that the official event no longer has a shirt and stickers that they send out).

> What is Hacktoberfest?
Hacktoberfest is open to everyone in our global community. Whether you’re a developer, student learning. During the entire month of October, all you have to do is contribute to any open source projects and open at least 4 pull requests. And you can win awesome prizes like a T-shirt, stickers, and coupons.
https://sef.discourse.group/t/it-s-hacktoberfest-month/543

Do you happen to see where they are offering their own swag?

**Comment by vimode** [comment]
I guess not, I thought since they mentioned *coupons* specifically it could be that those prizes were from them.

**Comment by crweiner** [comment]
Yeah, that bit threw me for a loop too. To keep things tidy, I'll close this Issue and PRs for now. But please do let me know if I got that wrong and they are offering their own swag so we can open the Issue back up! 😄 👍
