### ISSUE TITLE
Add to flutter_deck Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#748]
[flutter_deck](https://twitter.com/mkobuolys/status/1709185864436171017) contributors will get rewarded.

Top 3 contributors will receive a free digital copy of Flutter cookbook. 

![image](https://github.com/crweiner/hacktoberfest-swag-list/assets/39148877/db441d00-07d2-42cd-a934-c465d99fbeea)

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by crweiner** [comment]
Thank you @vimode! Added in PR #749
