### ISSUE TITLE
Add Devtron to Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#756]
[Devtron](https://twitter.com/DevtronL/status/1709402669767651466) is participating in Hacktoberfest 2023.

![Devtron tweet on Twitter](https://github.com/crweiner/hacktoberfest-swag-list/assets/39148877/2c948187-c757-4d57-afb6-c9fdce096a59)

They haven't announced the swag yet, but you can start contributing in various way to win some exclusive swag.

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by Mrinank-Bhowmick** [comment]
Can I get assigned
