### ISSUE TITLE
Add Hasura to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#760]
[Hasura](https://github.com/hasura/supergraph-top-n-challenge/blob/master/README.md) announced a challenge during Hacktobestfest 2023! 

But unsure if this counts towards hactoberfest PRs. 

ref [tweet](https://twitter.com/HasuraHQ/status/1709565871306227985)

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by aman44444** [comment]
@crweiner can i work on this ?

**Comment by Suraj-kumar00** [comment]
Hi @vimode, How are you doing?
Can I work on this issue, I saw no one is working on this issue can you please assign it to me? I would  love  to work on this!

**Comment by vimode** [comment]
Hey @aman44444 and @Suraj-kumar00 these are open issues for anyone to pick and start working. 
Please check the active PRs, and if an issue hasn't been picked up you are free to pick one. 

Just comment on the ones you are working on so others don't work on the same one. 

Thank you.
