### ISSUE TITLE
Add Featureform to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#771]
[Featureform](https://www.featureform.com/hacktoberfest-2023) is participating in the Hacktoberfest 2023!

All accepted submissions will receive a commemorative swag package and entry to a $500 raffle!

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by Sugamgoel28** [comment]
Hello, I would like to work on this issue, I'm right on it.

**Comment by Sugamgoel28** [comment]
@vaibhav-009 as I previously mentioned and commented, I was already working on issue #771. I find it unexpected that you submitted a PR without prior discussion. Additionally, I noticed that you've submitted a duplicate PR for Airbyte. I believe that such open-source contributions, which go against the collaborative spirit, lack meaningful value.

**Comment by vaibhav-009** [comment]
I have already resolved the issue before you commented and there is only a few minutes difference between your comment and my PR. You can check the timeline and for the Airbyte issue the one before me has merge conflicts so I also submitted a PR. Let the owner of repo decide which one to merge or not. Instead of commenting here you can find other issues also.

**Comment by crweiner** [comment]
[Issues are not assigned to one person](https://hacktoberfestswaglist.com/contributing/#other-contributing-guidelines), so anyone is free to submit a PR. 😄 I'll merge the best one, but if there are _two really great PRs_, then I may combine the best features from both and still assign credit via the `hacktoberfest-accepted` label. Feel free to submit whatever you would like for me to review! 👀
