### ISSUE TITLE
Add Loft Labs to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#772]
Loft Labs is participating in the Hacktoberfest 2023!

Contributions to their any of the Loft Labs open source projects, vCluster and devpod projects and get prizes for every merged PR.

ref [Loft Labs on twitter](https://twitter.com/loft_sh/status/171033134552680071)

![loft prizes](https://github.com/crweiner/hacktoberfest-swag-list/assets/39148877/45764603-0305-4f9c-9cc3-c5b840e47d71)

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by Sugamgoel28** [comment]
Hi, I'm working on this issue.

**Comment by ikunal-04** [comment]
Hi, I'm working on this issue, and adding Loft Labs to the Hacktoberfest swag lists
