### ISSUE TITLE
Add Stack Builders to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#773]
[Stack Builders](https://www.stackbuilders.com/hacktoberfest/) is participating in the Hacktoberfest 2023 by giving away gift cards for contributing to any of their projects.

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

**Comment by yashwanthvarma18** [comment]
hey can i contribute to this issue @vimode
