### ISSUE TITLE
Add SurrealDB in the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#786]
[SurrealDB](https://github.com/surrealdb/awesome-surreal/issues/35) is participating in Hacktoberfest 2023!

Create starter kits that integrate SurrealDB for a chance to win swag from their swag store.

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

Please check the [active PRs](https://github.com/crweiner/hacktoberfest-swag-list/pulls) to make sure there isn't already an active PR for this issue.

**Comment by vaibhav-009** [comment]
I am working on it
