### ISSUE TITLE
Add KodaDot to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#787]
[KodaDot](https://github.com/kodadot/nft-gallery/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest) is participating in Hacktoberfest 2023!

They provide cash bounty for some issues made available for hacktoberfest.

![KodaDot on twitter](https://github.com/crweiner/hacktoberfest-swag-list/assets/39148877/1fddec9a-bbf9-4ffe-b865-2d453f42f0a4)

[ref](https://twitter.com/KodaDot/status/1709221897081340131)

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

Please check the [active PRs](https://github.com/crweiner/hacktoberfest-swag-list/pulls) to make sure there isn't already an active PR for this issue.

**Comment by vaibhav-009** [comment]
I am working on it
