### ISSUE TITLE
Add Truffle Security to Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#796]
[Truffle Security Co.](https://github.com/trufflesecurity/hacktoberfest2023/blob/main/README.md) is participating in Hacktoberfest 2023 with the TruffleHog Detector Competition. 

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

Please check the [active PRs](https://github.com/crweiner/hacktoberfest-swag-list/pulls) to make sure there isn't already an active PR for this issue.

**Comment by vaibhav-009** [comment]
I am working on it

**Comment by Keshav-Pahwa** [comment]
I am working on it.
