### ISSUE TITLE
Add LeapFrog to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#806]
[LeapFrog](https://frogtoberfest.lftechnology.com/) is participating in Hacktoberfest 2023!

The registration form isn't accessible at the moment. So I think its better to wait till thats open and then add to the list.

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

Please check the [active PRs](https://github.com/crweiner/hacktoberfest-swag-list/pulls) to make sure there isn't already an active PR for this issue.

**Comment by Keshav-Pahwa** [comment]
i am working on it
