### ISSUE TITLE
Add Revert to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#830]
[Revert](https://twitter.com/revertdotdev/status/1712834581383233988) is participating in Hacktoberfest 2023! 

Merged issues will be awarded credits which can be redeemed at their swag store.

![Revert swag](https://github.com/crweiner/hacktoberfest-swag-list/assets/39148877/f0424dfa-18cc-458c-bbf1-b613acc589eb)

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

Please check the [active PRs](https://github.com/crweiner/hacktoberfest-swag-list/pulls) to make sure there isn't already an active PR for this issue.

**Comment by nooras** [comment]
Hi
Is it open for hacktoberfest ? Can i work on this issue ? Can you please assign me ?
Thanks

**Comment by nooras** [comment]
Hi @vimode 
Kindly please check the PR. Let me know in case of any changes are required.
Thanks
