### ISSUE TITLE
Add Zilliz to Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#831]
[Zilliz](https://zilliz.com/hacktoberfest) is participating in Hacktoberfest 2023 with their Milvus project!

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

Please check the [active PRs](https://github.com/crweiner/hacktoberfest-swag-list/pulls) to make sure there isn't already an active PR for this issue.

**Comment by shubhusion** [comment]
@vimode assign this issue to me

**Comment by vimode** [comment]
@shubhusion Issues are open for anyone to work on. Please read the contributing guide before starting. Thank you.
