### ISSUE TITLE
Add Taipy to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#838]
[Taipy](https://github.com/Avaiga/taipy/issues/330) is participating in Hacktoberfest 2023! 

Make meaningful contributions, first 10 merged PRs with receive a limited edition T-Shirt.

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

Please check the [active PRs](https://github.com/crweiner/hacktoberfest-swag-list/pulls) to make sure there isn't already an active PR for this issue.

**Comment by ansarisadaffatima** [comment]
Hi @vimode 
I will soon raise a PR for this issue.
Thanks
