### ISSUE TITLE
Add Vesoft to Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#842]
[Vesoft](https://github.com/vesoft-inc/nebula-community/wiki/HACKTOBERFEST2023) is participating in Hacktoberfest 2023!

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

Please check the [active PRs](https://github.com/crweiner/hacktoberfest-swag-list/pulls) to make sure there isn't already an active PR for this issue.

**Comment by devxiexie** [comment]
I'd like to work on this issue
