### ISSUE TITLE
Add Ultimate-Web-Development-Resources to Hacktoberfest Swag List

### ISSUE THREAD

**Issue by SoulNikhar** [crweiner/hacktoberfest-swag-list#847]
[Ultimate-Web-Development-Resources](https://github.com/DhanushNehru/Ultimate-Web-Development-Resources) is participating in Hacktoberfest 2023!

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

Please check the [active PRs](https://github.com/crweiner/hacktoberfest-swag-list/pulls) to make sure there isn't already an active PR for this issue.

**Comment by SoulNikhar** [comment]
Hii @crweiner, I have added a new GitHub repo which is currently participating in Hactoberfest 2023.

**Comment by vimode** [comment]
hey @SoulNikhar 

This project is not a list of hacktoberfest participating projects.
Please read the [README](https://github.com/crweiner/hacktoberfest-swag-list#what-is-the-hacktoberfest-swag-list) properly. 

Thank you.

**Comment by crweiner** [comment]
Hi @SoulNikhar, @vimode  is correct that [Ultimate-Web-Development-Resources](https://github.com/DhanushNehru/Ultimate-Web-Development-Resources) is not approprate for this project. In fact, it seems to completely go against the Hacktoberfest rules by being a dump of completely random code. So, I've reported it for exclusion towards Hacktoberfest as a whole. 👍

**Comment by SoulNikhar** [comment]
> Hi @SoulNikhar, @vimode is correct that [Ultimate-Web-Development-Resources](https://github.com/DhanushNehru/Ultimate-Web-Development-Resources) is not approprate for this project. In fact, it seems to completely go against the Hacktoberfest rules by being a dump of completely random code. So, I've reported it for exclusion towards Hacktoberfest as a whole. 👍

Please don't do that; otherwise, many participants may lose their points. give them warning to not do that.
thank you
