### ISSUE TITLE
Add WeVis to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#848]
[WeVis](https://github.com/wevisdemo/parliament-watch) is participating in Hacktoberfest 2023!

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

Please check the [active PRs](https://github.com/crweiner/hacktoberfest-swag-list/pulls) to make sure there isn't already an active PR for this issue.

**Comment by Rohxn16** [comment]
i wanna work on this please assign this to me. Any more details on this issue would also be appreciated.

**Comment by vimode** [comment]
Hey @Rohxn16 
Issues are not assigned on this repo, please read the contributing guidelines to learn how to contribute to this repo. Thank you.

**Comment by Rohxn16** [comment]
ok sure
