### ISSUE TITLE
Add Layer5 to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#878]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://layer5.io/programs/hacktoberfest), Layer5 is joining in on the Hacktoberfest fun by giving away their own swag for meaningful contributions. 😄 

Please add them to the 2024 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by SanchitMahajan236** [comment]
Please assign me this issue, I would love to contribute.

**Comment by vimode** [comment]
@crweiner  I don't see any mention of swag anymore as I recall it was before. Its just a badge, which might just be a holopin. 

Should I still add it to the list?
