### ISSUE TITLE
Add Configu to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#887]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://github.com/configu/configu/issues/465), Configu is joining in on the Hacktoberfest fun by giving away their own swag for meaningful contributions. 😄 

Please add them to the 2024 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by SanchitMahajan236** [comment]
I would love to work on this issue. Please assign me this issue

**Comment by crweiner** [comment]
Hi @SanchitMahajan236 ,  no issues are assigned, they are all first-come-first-served. Feel free to submit a PR that follows the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)!
