### ISSUE TITLE
Add Crawlee for Python to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by crweiner** [crweiner/hacktoberfest-swag-list#892]
A good first issue for people celebrating Hacktoberfest!

Per [here](https://github.com/apify/crawlee-python/issues/555), Crawlee for Python is joining in on the Hacktoberfest fun by giving away their own swag for meaningful contributions. 😄 

Please add them to the 2024 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by ovindu-a** [comment]
I can work on this @crweiner

**Comment by crweiner** [comment]
Howdy @ovindu-a 👋 . Per the [Contributing guide](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md#other-contributing-guidelines), work won't be assigned to any one person, it's all first-come-first-served (for the most part, based on the quality of the PRs), so feel free to work on this and raise a PR when you're done! 👍

**Comment by ovindu-a** [comment]
Ohh nice, I'll do that then. Thank you
