### ISSUE TITLE
Add Truffle Security to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#905]
A good first issue for people celebrating Hacktoberfest!

[Truffle Security](https://trufflesecurity.com/blog/hacktoberfest-2024-detector-improvement-competition-at-truffle-security) is once again joining Hacktoberfest! Enter the detector improvement competition by making valid PRs to earn a point. Earn points to win prizes like laptop, backpack, gift card and other swag. 🎉 

Please add them to the 2024 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md?rgh-link-date=2024-10-01T09%3A00%3A20Z)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by hemanthhhhhh** [comment]
Can I please contribute to this and please add the hacktoberfest label to it

**Comment by vimode** [comment]
Hey @hemanthhhhhh please read the [Contributing guide](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md?rgh-link-date=2024-10-01T06%3A18%3A23Z#other-contributing-guidelines). It's all first-come-first-served (for the most part, based on the quality of the PRs), so feel free to work on this and raise a PR when you're done.

All issues in this repo are hacktoberfest eligible.
