### ISSUE TITLE
Add dstack to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#907]
A good first issue for people celebrating Hacktoberfest!

[dstack](https://github.com/dstackai/dstack/issues/1735) are joining the Hacktoberfest! Contribute to dstack and get rewarded $10-$500 in GPU credits 🎉 

Please add them to the 2024 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md?rgh-link-date=2024-10-01T09%3A00%3A20Z)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by githubashutoshsoni** [comment]
hi, can I take this up?

**Comment by crweiner** [comment]
Added in #938
