### ISSUE TITLE
Add JavaScript Today to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#915]
A good first issue for people celebrating Hacktoberfest!

[JavaScript Today](https://javascripttoday.com/blog/hacktoberfest-2024-free-sticker/) is joining the Hacktoberfest! Make 4 valid and meaningful contributions to open source projects a Github or Gitlab to win stickers. 🎉

Please add them to the 2024 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md?rgh-link-date=2024-10-01T16%3A28%3A24Z)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by githubashutoshsoni** [comment]
Hey, Can I take this up.

**Comment by crweiner** [comment]
Hi @githubashutoshsoni , no issues are assigned, they are all first-come-first-served. Feel free to submit a PR that follows the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)!

**Comment by githubashutoshsoni** [comment]
Hi please check in this PR #918

**Comment by vimode** [comment]
#918
