### ISSUE TITLE
Add Refact to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#922]
A good first issue for people celebrating Hacktoberfest!

[Refact-LSP](https://github.com/smallcloudai/refact-lsp?tab=readme-ov-file#wave-welcome-hacktoberfest-contributors) are joining the Hacktoberfest! If you submit just one Pull Request (PR) to any of their open issues, they will reward you with 3 months of free access to the [Refact.ai](https://refact.ai/) tool! 🚀 🎉

Please add them to the 2024 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md?rgh-link-date=2024-10-01T16%3A28%3A24Z)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by githubashutoshsoni** [comment]
hey @crweiner please check #931
