### ISSUE TITLE
Css is broken on the site

### ISSUE THREAD

**Issue by prog1dev** [crweiner/hacktoberfest-swag-list#93]
[Here](https://user-images.githubusercontent.com/8070553/66002199-d1170c80-e4ab-11e9-80b3-846b2635527a.png) is a screenshot

Browser: Chrome 77.0.3865.90
OS: MacOS

**Comment by crweiner** [comment]
Hay @prog1dev!

Yes, I'm aware of this issue (which is more of a screen size issue than a CSS issue, kinda), which seems to occur in laptop screens around 13 inches. Are you on a Mac with a 13" screen? If you resize your browser window so it's narrower like a phone screen, then you'll see how the site adapts responsively. It also displays properly on larger screens greater than 15.4 inches.

If you have any ideas on how to get this to all fit properly on smaller laptop screens, I'd love to know! Feel free to submit a PR with your fixes too!!!

Thanks!

**Comment by prog1dev** [comment]
> Are you on a Mac with a 13" screen?

Yea

**Comment by crweiner** [comment]
> > Are you on a Mac with a 13" screen?
> 
> Yea. You can mark this issue with Hacktoberfest label

Good idea as it'll draw more people to help. :smile: Looking forward to you playing around with it and offering a potential fix. I have a 13" Mac too and I've tried but gave up...

**Comment by dehrax** [comment]
I'd suggest adding a media query for the resolution at which it breaks, and make the footer `position: none` and `width: 100%`. It will then be at the bottom instead.

**Comment by crweiner** [comment]
> I'd suggest adding a media query for the resolution at which it breaks, and make the footer `position: none` and `width: 100%`. It will then be at the bottom instead.

If you'd like to take a stab at it, be my guest! Netlify will build a preview for you when you submit a PR so you can play around with it and see how things look. :smile: :computer:

**Comment by dehrax** [comment]
Where should I put the CSS? In the Html file?

**Comment by crweiner** [comment]
> Where should I put the CSS? In the Html file?

When the site is built, Jekyll/Netlify uses the [pages-themes/minimal](https://github.com/pages-themes/minimal) theme and the [default.html](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/_layouts/default.html) template to transform the .md files to HTML. You can add custom styles [per the steps here](https://github.com/pages-themes/minimal#stylesheet) and reference that in the `<HEAD>` of [default.html](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/_layouts/default.html)

[This page on the Jekyll site](https://jekyllrb.com/docs/step-by-step/07-assets/) is also helpful to learn how to insert CSS/Sass during the build. :smile: 

If you don't want to set up a local Jekyll environment to test these out, you're welcome to start a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) so Netlify can provide you with a live deploy preview and you can push as many commits as you want. :+1:
