### ISSUE TITLE
Add QuestDB to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#933]
A good first issue for people celebrating Hacktoberfest!

[QuestDB](https://questdb.io/blog/hacktoberfest-2024-questdb/) is participating in Hacktoberfest 2024! Contribute to one of the three participating repos to win a T-shirt for your contribution! 🎉 

Please add them to the 2024 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md?rgh-link-date=2024-10-01T05%3A47%3A31Z)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by Brijeshthummar02** [comment]
assign me to the task.

**Comment by githubashutoshsoni** [comment]
Hi @crweiner , I have created my attempt here. Please check 

#940

**Comment by vimode** [comment]
hey @githubashutoshsoni please don't tag maintainers to check for PRs. They will at their convenience. Be patient.

**Comment by crweiner** [comment]
Added in #940
