### ISSUE TITLE
Add KitOps to Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#955]
A good first issue for people celebrating Hacktoberfest!

[KitOps](https://x.com/Kit_Ops/status/1841918765769920962) is participating in Hacktoberfest 2024! Contribute to the project to enter a raffle to win prizes like a T-shirt 🎉

Please add them to the 2024 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md?rgh-link-date=2024-10-09T15%3A52%3A51Z)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by stevenanthonyrevo** [comment]
Hi @vimode feel free to assign to me, I'd like to contribute!
