### ISSUE TITLE
Add Nuclei to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#958]
A good first issue for people celebrating Hacktoberfest!

[ProjectDiscovery](https://x.com/pdnuclei/status/1842248331935805919) is participating in Hacktoberfest 2024! Submit new [Nuclei Templates](https://github.com/projectdiscovery/nuclei-templates) to win stickers and other swag! 🎉

![PD Nuclei on X](https://github.com/user-attachments/assets/f756e3ba-2aa1-437a-a60c-4669d1093aa8)

Please add them to the 2024 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md?rgh-link-date=2024-10-12T02%3A14%3A18Z)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by githubashutoshsoni** [comment]
#960 closes this. please check
