### ISSUE TITLE
Add Portkey AI

### ISSUE THREAD

**Issue by ashirwad19** [crweiner/hacktoberfest-swag-list#962]
'tis the time of Hacktoberfest 2024

We are giving away Airpods Pro & select Portkey swag to Gateway contributors this month 🎁

Blog: https://portkey.ai/blog/portkey-hacktoberfest-24/
LInk to repo: https://git.new/portkey

**Comment by vimode** [comment]
Thanks for adding this issue, 🎉 Its already in the list of issues re: #951 
PR #953 closes it!

**Comment by stevenanthonyrevo** [comment]
Hi @vimode I'll contribute, please assign.

**Comment by crweiner** [comment]
Added in #953
