### ISSUE TITLE
Add Daytona to the Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#966]
A good first issue for people celebrating Hacktoberfest!

[Daytona](https://github.com/daytonaio/daytona/labels/hacktoberfest) is participating in Hacktoberfest 2024 by providing bounties (cash prizes) to hacktoberfest labeled issues! 🎉

Please add them to the 2024 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md?rgh-link-date=2024-10-11T05%3A49%3A40Z)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by mreguly** [comment]
I can do this, please assign me.

**Comment by vimode** [comment]
hey @mreguly issues aren't assigned, you are free to open a PR against open issues.

Please read the rule of contributing at [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to make sure you make a valid PR.
