### ISSUE TITLE
Add widgetbook to Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#967]
A good first issue for people celebrating Hacktoberfest!

[widgetbook](https://x.com/widgetbook_io/status/1846506614284497260) is participating in Hacktoberfest 2024! Contribute to the project to win some merch 🎉 Merch details are not provided as of now.

![widgetbook on X](https://github.com/user-attachments/assets/0692d9dd-18bb-46b3-adf4-9fa00043b984)

Please add them to the 2024 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md?rgh-link-date=2024-10-11T05%3A49%3A40Z)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

**Comment by mreguly** [comment]
I can do this, please assign me.
